// ============================================ 
// 📜 COMMAND REGISTRY - PERSONABOT
// Maps commands to categories, descriptions, and usage
// ============================================ 

const COMMAND_REGISTRY = {
  SUPPORT: [
    { cmd: 'support', desc: 'Get support and contact the creator directly.', usage: 'support' },
    { cmd: 'about', desc: 'Detailed information about the bot, its features, and creator.', usage: 'about' },
    { cmd: 'accept', desc: 'Accept any pending invitations (Guilds, Duels, Loans).', usage: 'accept' },
    { cmd: 'decline', desc: 'Decline any pending invitations.', usage: 'decline' }
  ],
  STICKERS: [
    { cmd: 's', desc: 'Create a sticker from an image/video OR search for images to stickerize.', usage: 's [count] [query]' },
    { cmd: 'toimg', desc: 'Convert a sticker back into an image.', usage: 'toimg (reply to sticker)' },
    { cmd: 'tovid', desc: 'Convert an animated sticker back into a video.', usage: 'tovid (reply to sticker)' }
  ],
  SEARCH: [
    { cmd: 'img', desc: 'Search for and download images.', usage: 'img <query>' },
    { cmd: 'audio', desc: 'Search for and download audio/music.', usage: 'audio <query>' },
    { cmd: 'anime search', desc: 'Search for any anime and get download links.', usage: 'anime search <name>' },
    { cmd: 'search', desc: 'Alias for anime search.', usage: 'search <name>' },
    { cmd: 'nsfw', desc: 'Search for NSFW content (Age-restricted).', usage: 'nsfw <count> <tag>' },
    { cmd: '18+', desc: 'Adult content search (Age-restricted).', usage: '18+ <tag>' }
  ],
  'PHANTOM THIEF': [
    { cmd: 'reveal', desc: 'Download and reveal a view-once image or video by replying to it.', usage: 'reveal' },
    { cmd: 'unmask', desc: 'Alias for reveal. Unmask a view-once message.', usage: 'unmask' },
    { cmd: 'steal', desc: 'Alias for reveal. Reveal a hidden view-once message.', usage: 'steal' }
  ],
  'USER INFO': [
    { cmd: 'profile', desc: 'View your or another user\'s profile, stats, and achievements.', usage: 'profile [@user]' },
    { cmd: 'me', desc: 'Alias for profile. View your own profile.', usage: 'me' },
    { cmd: 'whois', desc: 'Alias for profile. Shows user information.', usage: 'whois @user' },
    { cmd: 'nickname', desc: 'Set a custom nickname for yourself in the bot system.', usage: 'nickname <name>' },
    { cmd: 'note', desc: 'Add a personal note to your profile.', usage: 'note <text>' },
    { cmd: 'likes', desc: 'Add things you like to your memory profile.', usage: 'likes <text>' },
    { cmd: 'dislikes', desc: 'Add things you dislike to your memory profile.', usage: 'dislikes <text>' },
    { cmd: 'hobby', desc: 'Add your hobbies to your memory profile.', usage: 'hobby <text>' },
    { cmd: 'personal', desc: 'Add personal facts to your memory profile.', usage: 'personal <text>' },
    { cmd: 'forget me', desc: 'Delete all your data and start fresh.', usage: 'forget me' }
  ],
  ADMIN: [
    { cmd: 'kick', desc: 'Remove a user from the group chat.', usage: 'kick @user' },
    { cmd: 'delete', desc: 'Delete a message by replying to it.', usage: 'delete (reply)' },
    { cmd: 'block', desc: 'Block a user from using any bot commands.', usage: 'block @user' },
    { cmd: 'unblock', desc: 'Unblock a user.', usage: 'unblock @user' },
    { cmd: 'blocklist', desc: 'View the list of all blocked users.', usage: 'blocklist' },
    { cmd: 'antilink', desc: 'Manage link protection and actions.', usage: 'antilink on/off/action' },
    { cmd: 'antispam', desc: 'Enable/disable anti-spam protection.', usage: 'antispam on/off' },
    { cmd: 'welcome', desc: 'Toggle welcome messages for new members.', usage: 'welcome on/off' },
    { cmd: 'setwelcome', desc: 'Set or view custom welcome message.', usage: 'setwelcome [text]' },
    { cmd: 'bye', desc: 'Toggle goodbye messages for leaving members.', usage: 'bye on/off' },
    { cmd: 'setbye', desc: 'Set or view custom goodbye message.', usage: 'setbye [text]' },
    { cmd: 'warn', desc: 'Give a warning to a member. 5 warnings = Kick.', usage: 'warn @user [reason]' },
    { cmd: 'resetwarn', desc: 'Reset warnings for a user.', usage: 'resetwarn @user' },
    { cmd: 'warnings', desc: 'Check warning count for a user.', usage: 'warnings @user' },
    { cmd: 'promote', desc: 'Promote a member to admin.', usage: 'promote @user' },
    { cmd: 'demote', desc: 'Demote an admin to member.', usage: 'demote @user' },
    { cmd: 'mute', desc: 'Mute a user for a specific duration.', usage: 'mute @user <time>' },
    { cmd: 'unmute', desc: 'Unmute a user immediately.', usage: 'unmute @user' },
    { cmd: 'tagall', desc: 'Mention every single person in the group.', usage: 'tagall' },
    { cmd: 'hidetag', desc: 'Send a message that tags everyone invisibly.', usage: 'hidetag <msg>' },
    { cmd: 'lock', desc: 'Only admins can send messages in the group.', usage: 'lock' },
    { cmd: 'unlock', desc: 'Everyone can send messages in the group.', usage: 'unlock' },
    { cmd: 'pin', desc: 'Pin a message in the group (Reply to msg).', usage: 'pin [24h/7d/30d]' },
    { cmd: 'news', desc: 'Toggle automatic anime news broadcasts.', usage: 'news on/off' }
  ],
  GUILDS: [
    { cmd: 'guild create', desc: 'Establish a new guild.', usage: 'guild create <name>' },
    { cmd: 'guild delete', desc: 'Disband your current guild (Owners only).', usage: 'guild delete' },
    { cmd: 'guild join', desc: 'Join an existing public guild.', usage: 'guild join <name>' },
    { cmd: 'guild leave', desc: 'Leave your current guild.', usage: 'guild leave' },
    { cmd: 'guild invite', desc: 'Invite a user to join your guild.', usage: 'guild invite @user' },
    { cmd: 'guild accept', desc: 'Accept a private guild invitation.', usage: 'guild accept' },
    { cmd: 'guild decline', desc: 'Decline a private guild invitation.', usage: 'guild decline' },
    { cmd: 'guild list', desc: 'List all active guilds.', usage: 'guild list' },
    { cmd: 'guild members', desc: 'View all members in your guild.', usage: 'guild members' },
    { cmd: 'guild tag', desc: 'Mention all members of your guild.', usage: 'guild tag <msg>' },
    { cmd: 'guild motto', desc: 'Set a custom slogan for your guild (Owners only).', usage: 'guild motto <text>' },
    { cmd: 'guild promote', desc: 'Promote a guild member to officer.', usage: 'guild promote @user' },
    { cmd: 'guild demote', desc: 'Demote a guild officer.', usage: 'guild demote @user' },
    { cmd: 'guild kick', desc: 'Kick a member from the guild.', usage: 'guild kick @user' },
    { cmd: 'guild title', desc: 'Set a custom title for a guild member.', usage: 'guild title @user <title>' },
    { cmd: 'guild titles', desc: 'View all custom titles in the guild.', usage: 'guild titles' },
    { cmd: 'guild ranks', desc: 'View guild ranking system.', usage: 'guild ranks' },
    { cmd: 'guild leaderboard', desc: 'View the top guilds by points.', usage: 'guild leaderboard' },
    { cmd: 'guild challenge', desc: 'Challenge another guild to a battle.', usage: 'guild challenge <guild> <type>' },
    { cmd: 'guild challenges', desc: 'View pending guild challenges.', usage: 'guild challenges' },
    { cmd: 'guild points', desc: 'Check your guild\'s current points.', usage: 'guild points' },
    { cmd: 'guild pointsboard', desc: 'Leaderboard of guilds by points.', usage: 'guild pointsboard' },
    { cmd: 'guild upgrade', desc: 'Upgrade guild buildings for bonuses.', usage: 'guild upgrade <id>' }
  ],
  RPG: [
    { cmd: 'character', desc: 'View your RPG character sheet, class, and stats.', usage: 'character' },
    { cmd: 'char', desc: 'Alias for character.', usage: 'char' },
    { cmd: 'stats', desc: 'View your detailed RPG stats.', usage: 'stats' },
    { cmd: 'abilities', desc: 'View your learned skills and ability tree.', usage: 'abilities' },
    { cmd: 'skills', desc: 'Alias for abilities.', usage: 'skills' },
    { cmd: 'monster guide', desc: 'View info about monsters you can encounter.', usage: 'monster guide' },
    { cmd: 'handbook', desc: 'The ultimate guide to playing the RPG.', usage: 'handbook' },
    { cmd: 'guide', desc: 'Quick start guide for new players.', usage: 'guide' },
    { cmd: 'lore', desc: 'Read the deep history of the world.', usage: 'lore' },
    { cmd: 'inventory', desc: 'View items, materials, and equipment in your bag.', usage: 'inventory' },
    { cmd: 'bag', desc: 'Alias for inventory.', usage: 'bag' },
    { cmd: 'dismantle', desc: 'Break down items into crafting materials.', usage: 'dismantle <id/#>' },
    { cmd: 'equip', desc: 'Equip an item from your inventory.', usage: 'equip <id/#> [slot]' },
    { cmd: 'unequip', desc: 'Unequip an item from a specific slot.', usage: 'unequip <slot>' },
    { cmd: 'shop', desc: 'Browse the shop for items and equipment.', usage: 'shop [category]' },
    { cmd: 'reset sprite', desc: 'Reroll your character sprite appearance.', usage: 'reset sprite' },
    { cmd: 'recipes', desc: 'View available crafting recipes.', usage: 'recipes [page]' },
    { cmd: 'craft', desc: 'Create equipment using materials.', usage: 'craft <id>' },
    { cmd: 'brew', desc: 'Create potions and consumables.', usage: 'brew <id>' },
    { cmd: 'mine', desc: 'Go on a mining expedition for ores.', usage: 'mine' },
    { cmd: 'source', desc: 'Find out where to get a specific item.', usage: 'source <id>' },
    { cmd: 'allocate', desc: 'Spend stat points to increase your power.', usage: 'allocate <stat> <n>' },
    { cmd: 'leaderboard', desc: 'RPG Level Leaderboard.', usage: 'leaderboard' },
    { cmd: 'lb', desc: 'Alias for leaderboard.', usage: 'lb' },
    { cmd: 'upgrade inv', desc: 'Expand your inventory slot capacity.', usage: 'upgrade inv' },
    { cmd: 'classes', desc: 'View the class tree and evolution paths.', usage: 'classes' },
    { cmd: 'guild board', desc: 'View your guild\'s daily monster hunting board.', usage: 'guild board' },
    { cmd: 'quest', desc: 'Start a group quest adventure.', usage: 'quest [Rank]' },
    { cmd: 'solo', desc: 'Start a solo quest adventure.', usage: 'solo [Rank]' },
    { cmd: 'join', desc: 'Join an active group quest.', usage: 'join' },
    { cmd: 'stop', desc: 'Cancel an active quest (Admins/Owners).', usage: 'stop' },
    { cmd: 'vote', desc: 'Vote on decisions during a quest.', usage: 'vote <n>' },
    { cmd: 'duel', desc: 'Challenge another player to a 1v1 RPG duel with optional stakes.', usage: 'duel @user [stake]' },
    { cmd: 'challenge', desc: 'Alias for duel.', usage: 'challenge @user [stake]' },
    { cmd: 'pvp', desc: 'Perform actions during an active duel.', usage: 'pvp <attack/ability/item> [n]' }
  ],
  GROUP: [
    { cmd: 'record', desc: 'Toggle message recording for summaries.', usage: 'record on/off' },
    { cmd: 'summary', desc: 'Generate an AI summary of recent messages.', usage: 'summary' },
    { cmd: 'recap', desc: 'Alias for summary.', usage: 'recap' },
    { cmd: 'activity', desc: 'View member activity statistics for this group.', usage: 'activity' },
    { cmd: 'active', desc: 'List the most active members.', usage: 'active' },
    { cmd: 'inactive', desc: 'List members who haven\'t spoken recently.', usage: 'inactive' }
  ],
  PROGRESSION: [
    { cmd: 'level', desc: 'Check your current level and XP progress.', usage: 'level [user]' },
    { cmd: 'rank', desc: 'View your Adventurer Rank and requirements.', usage: 'rank' },
    { cmd: 'xptop', desc: 'XP Leaderboard - See the top players.', usage: 'xptop' },
    { cmd: 'gptop', desc: 'GP Leaderboard - See the top contributors.', usage: 'gptop' },
    { cmd: 'achievements', desc: 'View your unlocked achievements.', usage: 'achievements' },
    { cmd: 'graveyard', desc: 'View the memorial of fallen hardcore heroes.', usage: 'graveyard' }
  ],
  ECONOMY: [
    { cmd: 'register', desc: 'Join the economy and RPG system.', usage: 'register <nickname>' },
    { cmd: 'balance', desc: 'Check your current Wallet and Bank balances.', usage: 'balance' },
    { cmd: 'bal', desc: 'Alias for balance.', usage: 'bal' },
    { cmd: 'history', desc: 'View your recent transaction history.', usage: 'history' },
    { cmd: 'bh', desc: 'Alias for history (Bank History).', usage: 'bh' },
    { cmd: 'daily', desc: 'Claim your daily reward.', usage: 'daily' },
    { cmd: 'deposit', desc: 'Move money from Wallet to Bank (Safe from robbing).', usage: 'deposit <amt>' },
    { cmd: 'dep', desc: 'Alias for deposit.', usage: 'dep <amt>' },
    { cmd: 'withdraw', desc: 'Move money from Bank to Wallet.', usage: 'withdraw <amt>' },
    { cmd: 'with', desc: 'Alias for withdraw.', usage: 'with <amt>' },
    { cmd: 'transfer', desc: 'Send currency to another user.', usage: 'transfer @user <amt>' },
    { cmd: 'send', desc: 'Alias for transfer.', usage: 'send @user <amt>' },
    { cmd: 'loan', desc: 'Request a loan from another user.', usage: 'loan @user <amt> <%> <time>' },
    { cmd: 'loan accept', desc: 'Accept a pending loan request.', usage: 'loan accept' },
    { cmd: 'loan decline', desc: 'Decline a pending loan request.', usage: 'loan decline' },
    { cmd: 'rob', desc: 'Attempt to rob another user\'s wallet.', usage: 'rob @user' },
    { cmd: 'steal', desc: 'Alias for rob. Rob another user.', usage: 'steal @user' },
    { cmd: 'rich', desc: 'Wealth Leaderboard - See the richest players.', usage: 'rich' },
    { cmd: 'richest', desc: 'Alias for rich.', usage: 'richest' },
    { cmd: 'gamblers', desc: 'Gamble Leaderboard - See the top winners.', usage: 'gamblers' },
    { cmd: 'lb gamble', desc: 'Alias for gamblers leaderboard.', usage: 'lb gamble' },
    { cmd: 'economy', desc: 'View global economy statistics and insights.', usage: 'economy' },
    { cmd: 'invest', desc: 'View investment plans or start an investment.', usage: 'invest [plan] [amt]' },
    { cmd: 'claim', desc: 'Claim your matured investments.', usage: 'claim' },
    { cmd: 'stocks', desc: 'View the stock market or your portfolio.', usage: 'stocks [buy/sell] [symbol] [amt]' }
  ],
  GAMBLING: [
    { cmd: 'cf', desc: 'Flip a coin and bet on Heads or Tails.', usage: 'cf <amt> <h/t>' },
    { cmd: 'flip', desc: 'Alias for cf. Flip a coin.', usage: 'flip <amt> <h/t>' },
    { cmd: 'dice', desc: 'Roll a dice against the bot.', usage: 'dice <amount>' },
    { cmd: 'roll', desc: 'Alias for dice. Roll a dice.', usage: 'roll <amount>' },
    { cmd: 'slots', desc: 'Classic slot machine game.', usage: 'slots <amount>' },
    { cmd: 'hl', desc: 'Guess if the next number is Higher or Lower.', usage: 'hl <amt> <h/l>' },
    { cmd: 'bj', desc: 'Play Blackjack against the dealer.', usage: 'bj <amount>' },
    { cmd: 'roulette', desc: 'Bet on colors or numbers in Roulette.', usage: 'roulette <amt> <bet>' },
    { cmd: 'roul', desc: 'Alias for roulette.', usage: 'roul <amt> <bet>' },
    { cmd: 'crash', desc: 'Multiplier game. Cash out before the crash!', usage: 'crash <amount>' },
    { cmd: 'mines', desc: 'Find diamonds and avoid mines in a 5x5 grid.', usage: 'mines <amt> <mines>' },
    { cmd: 'plinko', desc: 'Drop a ball and hope for a high multiplier.', usage: 'plinko <amt> <risk>' },
    { cmd: 'scratch', desc: 'Buy a virtual scratch card.', usage: 'scratch <amt>' },
    { cmd: 'cups', desc: 'Find the ball under three moving cups.', usage: 'cups <amt> <1-3>' },
    { cmd: 'wheel', desc: 'Spin the Wheel of Fortune.', usage: 'wheel <amt>' },
    { cmd: 'horse', desc: 'Bet on a horse race.', usage: 'horse <amt> <1-5>' },
    { cmd: 'lotto', desc: 'Participate in the lottery for a huge jackpot.', usage: 'lotto <amount>' },
    { cmd: 'rps', desc: 'Rock Paper Scissors against the bot.', usage: 'rps <amt> <r/p/s>' },
    { cmd: 'penalty', desc: 'Score a penalty goal against the bot.', usage: 'penalty <amt> <l/c/r>' },
    { cmd: 'guess', desc: 'Guess a number between 1-10.', usage: 'guess <amt> <1-10>' }
  ],
  CARDS: [
    { cmd: 'claim', desc: 'Claim a spawned card by its ID.', usage: 'claim <id>' },
    { cmd: 'coll', desc: 'View your full card collection.', usage: 'coll' },
    { cmd: 'card --tier', desc: 'View your collection sorted by tier.', usage: 'card --tier' },
    { cmd: 'deck', desc: 'View your 12-slot main card deck.', usage: 'deck' },
    { cmd: 't2deck', desc: 'Move a card from collection to main deck.', usage: 't2deck <coll#>' },
    { cmd: 't2coll', desc: 'Move a card from main deck back to collection.', usage: 't2coll <deck#>' },
    { cmd: 'swap card', desc: 'Rearrange cards in your main deck.', usage: 'swap card <a> and <b>' },
    { cmd: 'buycard', desc: 'Browse the card market or buy a listing.', usage: 'buycard [n]' },
    { cmd: 'sc', desc: 'List a card from your deck for sale.', usage: 'sc <slot> <price>' },
    { cmd: 'cancel sale', desc: 'Remove your active sale listing.', usage: 'cancel sale' },
    { cmd: 'bid', desc: 'Place a bid on an active card auction.', usage: 'bid <amount>' },
    { cmd: 'merge', desc: 'Combine 2 copies of the same card into 1 better copy.', usage: 'merge <id>' },
    { cmd: 'cs', desc: 'Search for card availability and stats.', usage: 'cs <name> [tier n]' },
    { cmd: 'cg', desc: 'Give a card from your deck to another user.', usage: 'cg @user Deck <n>' },
    { cmd: 'cltr', desc: 'See top collectors of a specific series.', usage: 'cltr <series>' },
    { cmd: 'list decks', desc: 'List all your custom card decks.', usage: 'list decks' },
    { cmd: 'create deck', desc: 'Create a new custom card deck.', usage: 'create deck <name>' },
    { cmd: 'cdeck', desc: 'View contents of a custom deck.', usage: 'cdeck <name> [slot]' },
    { cmd: 'rename deck', desc: 'Rename one of your custom decks.', usage: 'rename deck <old> | <new>' },
    { cmd: 'delete deck', desc: 'Delete a custom deck (Cards inside are deleted!).', usage: 'delete deck <name>' }
  ],
  FUN: [
    { cmd: 'joke', desc: 'Get a random funny joke.', usage: 'joke' },
    { cmd: 'truth', desc: 'Get a Truth or Dare truth question.', usage: 'truth' },
    { cmd: 'dare', desc: 'Get a Truth or Dare dare challenge.', usage: 'dare' },
    { cmd: 'roast', desc: 'AI-powered roast of a user.', usage: 'roast @user' },
    { cmd: 'ship', desc: 'Calculate the love compatibility between two people.', usage: 'ship @u1 @u2' },
    { cmd: 'fact', desc: 'Get a random interesting fact.', usage: 'fact' },
    { cmd: 'define', desc: 'Get the definition of a word.', usage: 'define <word>' },
    { cmd: 'rate', desc: 'Let the bot rate anything.', usage: 'rate <thing>' },
    { cmd: '8ball', desc: 'Ask the magic 8-ball a question.', usage: '8ball <q>' },
    { cmd: 'motivate', desc: 'Get a motivational quote.', usage: 'motivate' },
    { cmd: 'fish', desc: 'Go scavenging at the coast for rare fish and shards.', usage: 'fish' },
    { cmd: 'hunt', desc: 'Track and capture wilderness animals for profit.', usage: 'hunt' }
  ],
  GAMES: [
    { cmd: 'ttt', desc: 'Play Tic-Tac-Toe (3x3 grid).', usage: 'ttt @user' },
    { cmd: 'tttt', desc: 'Play Tic-Tac-Toe (8x8 grid).', usage: 'tttt @user' },
    { cmd: 'ttttt', desc: 'Play Tic-Tac-Toe (16x16 grid).', usage: 'ttttt @user' },
    { cmd: 'move', desc: 'Make a move in an active game.', usage: 'move <cell>' },
    { cmd: 'ttt scores', desc: 'View the Tic-Tac-Toe leaderboard.', usage: 'ttt scores' },
    { cmd: 'ttt end', desc: 'Quit an active Tic-Tac-Toe game.', usage: 'ttt end' },
    { cmd: 'ludo start', desc: 'Start a Ludo game with friends.', usage: 'ludo start @u1 @u2...' },
    { cmd: 'ludo roll', desc: 'Roll the dice in Ludo.', usage: 'ludo roll' },
    { cmd: 'ludo move', desc: 'Move a piece in Ludo.', usage: 'ludo move <#>' },
    { cmd: 'ludo board', desc: 'Show the current Ludo board.', usage: 'ludo board' },
    { cmd: 'ludo end', desc: 'Quit an active Ludo game.', usage: 'ludo end' },
    { cmd: 'wordle', desc: 'Start a Wordle game (Easy/Med/Hard).', usage: 'wordle [difficulty]' },
    { cmd: 'wordle board', desc: 'Show your current Wordle board.', usage: 'wordle board' },
    { cmd: 'wordle end', desc: 'Quit an active Wordle game.', usage: 'wordle end' },
    { cmd: 'wordle s', desc: 'Check your Wordle stats.', usage: 'wordle s' },
    { cmd: 'wordle top', desc: 'View the Wordle leaderboard.', usage: 'wordle top' }
  ],
  PowerScaling: [
    { cmd: 'powerscale', desc: 'Get character power stats.', usage: 'powerscale <char>' },
    { cmd: 'debate on', desc: 'Start an AI-judged debate between two users.', usage: 'debate on <topic>' },
    { cmd: 'debate off', desc: 'Cancel an active debate.', usage: 'debate off' },
    { cmd: 'debate leaderboard', desc: 'View the debate rankings.', usage: 'debate leaderboard' },
    { cmd: 'judge', desc: 'Let the AI judge the current debate.', usage: 'judge' }
  ],
  ANIME: [
    { cmd: 'anime news', desc: 'Get the latest anime news and updates.', usage: 'anime news' },
    { cmd: 'anime trending', desc: 'See what anime is hot right now.', usage: 'anime trending' },
    { cmd: 'anime airing', desc: 'List currently airing anime.', usage: 'anime airing' },
    { cmd: 'anime upcoming', desc: 'View upcoming anime releases.', usage: 'anime upcoming' },
    { cmd: 'anime top', desc: 'View the top-ranked anime of all time.', usage: 'anime top' },
    { cmd: 'anime random', desc: 'Get a random anime recommendation.', usage: 'anime random' },
    { cmd: 'anime studio', desc: 'Find anime by a specific studio.', usage: 'anime studio <name>' },
    { cmd: 'anime search', desc: 'Search for any anime.', usage: 'anime search <name>' },
    { cmd: 'anime rank', desc: 'Check details of an anime\'s rank.', usage: 'anime rank <name>' }
  ],
  INFO: [
    { cmd: 'menu', desc: 'Show the bot command menu and categories.', usage: 'menu [category]' },
    { cmd: 'help', desc: 'Alias for menu. Shows help information.', usage: 'help [category]' },
    { cmd: 'reset', desc: 'Reset the bot connection/session.', usage: 'reset' },
    { cmd: 'on', desc: 'Turn the bot ON for this chat.', usage: 'on' },
    { cmd: 'off', desc: 'Turn the bot OFF for this chat.', usage: 'off' }
  ]
};

module.exports = COMMAND_REGISTRY;
