// ============================================
// THEME SONG POOL (2026-09-27, owner brief §2 & §3)
// ============================================
// ".audio mode" = theme songs ACROSS ALL OF FICTION: anime openings, TV
// show themes, movie scores, game soundtracks. Each entry:
//   { show }   - the display answer ("Which show is this theme from?")
//   { search } - what the Go audio service searches (biased toward the
//                canonical upload)
//   { type }   - anime | tv | movie | game (distractor preference)
// Verification is the same P14-style gate as Spot the Song: the returned
// metadata must overlap the search terms and no cover/karaoke/nightcore
// markers may be present.
// ============================================

const THEMES = [
  // ---- anime ----
  { show: "Attack on Titan", search: "Attack on Titan opening theme", type: "anime" },
  { show: "Demon Slayer", search: "Demon Slayer opening theme", type: "anime" },
  { show: "Jujutsu Kaisen", search: "Jujutsu Kaisen opening theme", type: "anime" },
  { show: "One Piece", search: "One Piece opening theme", type: "anime" },
  { show: "Naruto Shippuden", search: "Naruto Shippuden opening theme", type: "anime" },
  { show: "Dragon Ball Z", search: "Dragon Ball Z opening theme", type: "anime" },
  { show: "Death Note", search: "Death Note opening theme", type: "anime" },
  { show: "Fullmetal Alchemist Brotherhood", search: "Fullmetal Alchemist Brotherhood opening theme", type: "anime" },
  { show: "One Punch Man", search: "One Punch Man opening theme", type: "anime" },
  { show: "Hunter x Hunter", search: "Hunter x Hunter opening theme", type: "anime" },
  { show: "Bleach", search: "Bleach anime opening theme", type: "anime" },
  { show: "My Hero Academia", search: "My Hero Academia opening theme", type: "anime" },
  { show: "Tokyo Ghoul", search: "Tokyo Ghoul opening theme", type: "anime" },
  { show: "Steins;Gate", search: "Steins Gate opening theme", type: "anime" },
  { show: "Code Geass", search: "Code Geass opening theme", type: "anime" },
  { show: "Cowboy Bebop", search: "Tank Cowboy Bebop opening", type: "anime" },
  { show: "Neon Genesis Evangelion", search: "Cruel Angel's Thesis Evangelion opening", type: "anime" },
  { show: "Sword Art Online", search: "Sword Art Online opening theme", type: "anime" },
  { show: "Re:Zero", search: "Re Zero opening theme", type: "anime" },
  { show: "Chainsaw Man", search: "Chainsaw Man opening theme", type: "anime" },
  { show: "Spy x Family", search: "Spy x Family opening theme", type: "anime" },
  { show: "Mob Psycho 100", search: "Mob Psycho 100 opening theme", type: "anime" },
  { show: "Vinland Saga", search: "Vinland Saga opening theme", type: "anime" },
  { show: "Haikyuu!!", search: "Haikyuu opening theme", type: "anime" },
  { show: "Kaguya-sama: Love Is War", search: "Kaguya Sama Love Is War opening theme", type: "anime" },
  { show: "Your Name", search: "Your Name Kimi no Nawa theme song", type: "anime" },
  { show: "A Silent Voice", search: "A Silent Voice theme song", type: "anime" },
  { show: "Spirited Away", search: "Spirited Away theme song", type: "anime" },
  { show: "Princess Mononoke", search: "Princess Mononoke theme song", type: "anime" },
  { show: "Berserk (1997)", search: "Berserk 1997 opening theme", type: "anime" },
  { show: "Fairy Tail", search: "Fairy Tail opening theme", type: "anime" },
  { show: "Black Clover", search: "Black Clover opening theme", type: "anime" },
  { show: "Dr. Stone", search: "Dr Stone opening theme", type: "anime" },
  { show: "Fire Force", search: "Fire Force opening theme", type: "anime" },
  { show: "Made in Abyss", search: "Made in Abyss opening theme", type: "anime" },
  { show: "Konosuba", search: "Konosuba opening theme", type: "anime" },
  // ---- TV ----
  { show: "Friends", search: "Friends theme song I'll Be There For You", type: "tv" },
  { show: "Game of Thrones", search: "Game of Thrones theme song", type: "tv" },
  { show: "Breaking Bad", search: "Breaking Bad theme song", type: "tv" },
  { show: "Stranger Things", search: "Stranger Things theme song", type: "tv" },
  { show: "The Office", search: "The Office US theme song", type: "tv" },
  { show: "Sherlock", search: "Sherlock BBC theme song", type: "tv" },
  { show: "Doctor Who", search: "Doctor Who theme song", type: "tv" },
  { show: "The Simpsons", search: "The Simpsons theme song", type: "tv" },
  { show: "SpongeBob SquarePants", search: "SpongeBob SquarePants theme song", type: "tv" },
  { show: "Rick and Morty", search: "Rick and Morty theme song", type: "tv" },
  { show: "Gravity Falls", search: "Gravity Falls theme song", type: "tv" },
  { show: "Adventure Time", search: "Adventure Time theme song", type: "tv" },
  { show: "Avatar: The Last Airbender", search: "Avatar The Last Airbender theme song", type: "tv" },
  { show: "Ben 10", search: "Ben 10 theme song", type: "tv" },
  { show: "Teen Titans", search: "Teen Titans theme song", type: "tv" },
  { show: "Peaky Blinders", search: "Peaky Blinders theme song Red Right Hand", type: "tv" },
  { show: "Money Heist", search: "Money Heist theme song Bella Ciao", type: "tv" },
  { show: "The Big Bang Theory", search: "The Big Bang Theory theme song", type: "tv" },
  { show: "How I Met Your Mother", search: "How I Met Your Mother theme song", type: "tv" },
  { show: "Brooklyn Nine-Nine", search: "Brooklyn Nine-Nine theme song", type: "tv" },
  { show: "Squid Game", search: "Squid Game theme song", type: "tv" },
  { show: "Wednesday", search: "Wednesday Addams theme song", type: "tv" },
  { show: "The Fresh Prince of Bel-Air", search: "Fresh Prince of Bel Air theme song", type: "tv" },
  { show: "Narcos", search: "Narcos theme song", type: "tv" },
  { show: "True Detective", search: "True Detective theme song", type: "tv" },
  { show: "The Wire", search: "The Wire theme song", type: "tv" },
  { show: "The Sopranos", search: "The Sopranos theme song", type: "tv" },
  { show: "Dark", search: "Dark Netflix theme song", type: "tv" },
  { show: "The Witcher", search: "The Witcher Netflix theme song", type: "tv" },
  { show: "Arcane", search: "Arcane League of Legends theme song", type: "tv" },
  { show: "Better Call Saul", search: "Better Call Saul theme song", type: "tv" },
  // ---- movies ----
  { show: "Star Wars", search: "Star Wars main theme John Williams", type: "movie" },
  { show: "Harry Potter", search: "Harry Potter Hedwig's Theme", type: "movie" },
  { show: "The Lord of the Rings", search: "Lord of the Rings main theme", type: "movie" },
  { show: "Pirates of the Caribbean", search: "Pirates of the Caribbean He's a Pirate theme", type: "movie" },
  { show: "Jurassic Park", search: "Jurassic Park theme John Williams", type: "movie" },
  { show: "Indiana Jones", search: "Indiana Jones theme John Williams", type: "movie" },
  { show: "The Godfather", search: "The Godfather theme song", type: "movie" },
  { show: "Titanic", search: "Titanic My Heart Will Go On instrumental", type: "movie" },
  { show: "The Lion King", search: "The Lion King Circle of Life", type: "movie" },
  { show: "Frozen", search: "Frozen Let It Go", type: "movie" },
  { show: "The Dark Knight", search: "The Dark Knight theme Hans Zimmer", type: "movie" },
  { show: "Inception", search: "Inception Time Hans Zimmer", type: "movie" },
  { show: "Interstellar", search: "Interstellar theme Hans Zimmer", type: "movie" },
  { show: "Gladiator", search: "Gladiator Now We Are Free theme", type: "movie" },
  { show: "James Bond", search: "James Bond 007 main theme", type: "movie" },
  { show: "Mission: Impossible", search: "Mission Impossible theme song", type: "movie" },
  { show: "Rocky", search: "Rocky Eye of the Tiger training theme", type: "movie" },
  { show: "Top Gun", search: "Top Gun Anthem theme", type: "movie" },
  { show: "Ghostbusters", search: "Ghostbusters theme song", type: "movie" },
  { show: "Back to the Future", search: "Back to the Future theme", type: "movie" },
  { show: "E.T.", search: "E.T. theme John Williams", type: "movie" },
  { show: "Jaws", search: "Jaws theme John Williams", type: "movie" },
  { show: "Superman", search: "Superman theme John Williams", type: "movie" },
  { show: "Batman 1989", search: "Batman 1989 theme Danny Elfman", type: "movie" },
  { show: "Spider-Man", search: "Spider-Man theme song", type: "movie" },
  { show: "The Avengers", search: "Avengers main theme Alan Silvestri", type: "movie" },
  { show: "Guardians of the Galaxy", search: "Guardians of the Galaxy Awesome Mix theme", type: "movie" },
  { show: "Coco", search: "Coco Remember Me theme", type: "movie" },
  { show: "Up", search: "Up Pixar Married Life theme", type: "movie" },
  { show: "Toy Story", search: "Toy Story You've Got a Friend in Me", type: "movie" },
  { show: "Shrek", search: "Shrek Hallelujah theme", type: "movie" },
  { show: "Aladdin", search: "Aladdin A Whole New World", type: "movie" },
  { show: "The Little Mermaid", search: "The Little Mermaid Under the Sea", type: "movie" },
  { show: "Beauty and the Beast", search: "Beauty and the Beast theme", type: "movie" },
  { show: "Mulan", search: "Mulan Reflection theme", type: "movie" },
  { show: "Spider-Verse", search: "Spider-Man Into the Spider-Verse theme", type: "movie" },
  { show: "Oppenheimer", search: "Oppenheimer theme Ludwig Goransson", type: "movie" },
  { show: "Dune", search: "Dune theme Hans Zimmer", type: "movie" },
  { show: "Mad Max: Fury Road", search: "Mad Max Fury Road theme", type: "movie" },
  { show: "The Matrix", search: "The Matrix theme Spybreak", type: "movie" },
  // ---- games ----
  { show: "Minecraft", search: "Minecraft Sweden C418 soundtrack", type: "game" },
  { show: "The Legend of Zelda", search: "Zelda main theme", type: "game" },
  { show: "Super Mario Bros.", search: "Super Mario Bros main theme", type: "game" },
  { show: "Sonic the Hedgehog", search: "Sonic the Hedgehog Green Hill Zone theme", type: "game" },
  { show: "Pokémon", search: "Pokemon anime theme song Gotta Catch Em All", type: "game" },
  { show: "Final Fantasy VII", search: "Final Fantasy VII One-Winged Angel", type: "game" },
  { show: "Final Fantasy X", search: "Final Fantasy X To Zanarkand", type: "game" },
  { show: "Elden Ring", search: "Elden Ring main theme", type: "game" },
  { show: "Dark Souls", search: "Dark Souls main theme", type: "game" },
  { show: "Bloodborne", search: "Bloodborne main theme", type: "game" },
  { show: "Sekiro", search: "Sekiro main theme", type: "game" },
  { show: "God of War", search: "God of War main theme", type: "game" },
  { show: "The Witcher 3", search: "Witcher 3 main theme", type: "game" },
  { show: "Skyrim", search: "Skyrim main theme Dovahkiin", type: "game" },
  { show: "Morrowind", search: "Morrowind main theme Nerevar Rising", type: "game" },
  { show: "Tetris", search: "Tetris theme Song Type A", type: "game" },
  { show: "Pac-Man", search: "Pac-Man theme song arcade", type: "game" },
  { show: "Undertale", search: "Undertale Megalovania", type: "game" },
  { show: "Mega Man", search: "Mega Man theme song NES", type: "game" },
  { show: "Street Fighter", search: "Street Fighter II theme Guile", type: "game" },
  { show: "Mortal Kombat", search: "Mortal Kombat theme song", type: "game" },
  { show: "Halo", search: "Halo main theme Martin O'Donnell", type: "game" },
  { show: "Mass Effect", search: "Mass Effect main theme", type: "game" },
  { show: "Cyberpunk 2077", search: "Cyberpunk 2077 main theme", type: "game" },
  { show: "Grand Theft Auto V", search: "GTA V main theme", type: "game" },
  { show: "Red Dead Redemption 2", search: "Red Dead Redemption 2 main theme", type: "game" },
  { show: "The Last of Us", search: "The Last of Us main theme Gustavo Santaolalla", type: "game" },
  { show: "Uncharted", search: "Uncharted main theme", type: "game" },
  { show: "Kingdom Hearts", search: "Kingdom Hearts Dearly Beloved", type: "game" },
  { show: "Genshin Impact", search: "Genshin Impact main theme", type: "game" },
  { show: "League of Legends", search: "League of Legends Worlds theme", type: "game" },
  { show: "Fortnite", search: "Fortnite main theme", type: "game" },
  { show: "Among Us", search: "Among Us theme song", type: "game" },
  { show: "Angry Birds", search: "Angry Birds theme song", type: "game" },
  { show: "Cuphead", search: "Cuphead main theme", type: "game" },
  { show: "Stardew Valley", search: "Stardew Valley theme song", type: "game" },
  { show: "Animal Crossing", search: "Animal Crossing main theme", type: "game" },
  { show: "Metroid", search: "Metroid main theme", type: "game" },
  { show: "Donkey Kong Country", search: "Donkey Kong Country theme Aquatic Ambience", type: "game" },
  { show: "Chrono Trigger", search: "Chrono Trigger main theme", type: "game" },
  { show: "Persona 5", search: "Persona 5 Last Surprise theme", type: "game" },
  { show: "Nier Automata", search: "NieR Automata Weight of the World", type: "game" },
  { show: "Doom", search: "Doom E1M1 theme", type: "game" },
  { show: "Portal", search: "Portal Still Alive theme", type: "game" },
  { show: "Assassin's Creed", search: "Assassin's Creed main theme", type: "game" },
  { show: "Far Cry 3", search: "Far Cry 3 main theme", type: "game" },
  { show: "Fallout", search: "Fallout main theme", type: "game" },
];

module.exports = { THEMES };
