// ============================================
// SPOT THE SONG POOL v2 (2026-09-27) - ~210 globally famous tracks
// ============================================
// Owner brief section 3: "a long list of songs that people are actually
// likely to recognize: popular songs, relevant songs, old-school songs,
// iconic songs". { song, artist, era } - era drives fair same-era
// distractors, (song + artist) drives the audio-service search.
// ============================================

const SONGS = [
  // 1960s
  { song: "Hey Jude", artist: "The Beatles", era: "1960s" },
  { song: "Let It Be", artist: "The Beatles", era: "1960s" },
  { song: "Yesterday", artist: "The Beatles", era: "1960s" },
  { song: "Come Together", artist: "The Beatles", era: "1960s" },
  { song: "Twist and Shout", artist: "The Beatles", era: "1960s" },
  { song: "I Want to Hold Your Hand", artist: "The Beatles", era: "1960s" },
  { song: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", era: "1960s" },
  { song: "Paint It Black", artist: "The Rolling Stones", era: "1960s" },
  { song: "My Generation", artist: "The Who", era: "1960s" },
  { song: "Good Vibrations", artist: "The Beach Boys", era: "1960s" },
  { song: "I Heard It Through the Grapevine", artist: "Marvin Gaye", era: "1960s" },
  { song: "Respect", artist: "Aretha Franklin", era: "1960s" },
  { song: "What a Wonderful World", artist: "Louis Armstrong", era: "1960s" },
  { song: "Ring of Fire", artist: "Johnny Cash", era: "1960s" },
  { song: "Stand by Me", artist: "Ben E. King", era: "1960s" },
  { song: "Suspicious Minds", artist: "Elvis Presley", era: "1960s" },
  { song: "My Girl", artist: "The Temptations", era: "1960s" },
  { song: "Ain't No Mountain High Enough", artist: "Marvin Gaye", era: "1960s" },
  { song: "The Sound of Silence", artist: "Simon & Garfunkel", era: "1960s" },
  { song: "House of the Rising Sun", artist: "The Animals", era: "1960s" },
  // 1970s
  { song: "Bohemian Rhapsody", artist: "Queen", era: "1970s" },
  { song: "We Will Rock You", artist: "Queen", era: "1970s" },
  { song: "Don't Stop Me Now", artist: "Queen", era: "1970s" },
  { song: "We Are the Champions", artist: "Queen", era: "1970s" },
  { song: "Imagine", artist: "John Lennon", era: "1970s" },
  { song: "Stairway to Heaven", artist: "Led Zeppelin", era: "1970s" },
  { song: "Hotel California", artist: "Eagles", era: "1970s" },
  { song: "Dancing Queen", artist: "ABBA", era: "1970s" },
  { song: "Mamma Mia", artist: "ABBA", era: "1970s" },
  { song: "Rocket Man", artist: "Elton John", era: "1970s" },
  { song: "Stayin' Alive", artist: "Bee Gees", era: "1970s" },
  { song: "Another Brick in the Wall", artist: "Pink Floyd", era: "1970s" },
  { song: "Wish You Were Here", artist: "Pink Floyd", era: "1970s" },
  { song: "Go Your Own Way", artist: "Fleetwood Mac", era: "1970s" },
  { song: "Dreams", artist: "Fleetwood Mac", era: "1970s" },
  { song: "Superstition", artist: "Stevie Wonder", era: "1970s" },
  { song: "Let's Stay Together", artist: "Al Green", era: "1970s" },
  { song: "Le Freak", artist: "Chic", era: "1970s" },
  { song: "I Will Survive", artist: "Gloria Gaynor", era: "1970s" },
  { song: "YMCA", artist: "Village People", era: "1970s" },
  { song: "September", artist: "Earth, Wind & Fire", era: "1970s" },
  { song: "American Pie", artist: "Don McLean", era: "1970s" },
  { song: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", era: "1970s" },
  { song: "Lean on Me", artist: "Bill Withers", era: "1970s" },
  { song: "Ain't No Sunshine", artist: "Bill Withers", era: "1970s" },
  { song: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", era: "1970s" },
  { song: "Free Bird", artist: "Lynyrd Skynyrd", era: "1970s" },
  { song: "Born to Run", artist: "Bruce Springsteen", era: "1970s" },
  { song: "Your Song", artist: "Elton John", era: "1970s" },
  { song: "Tiny Dancer", artist: "Elton John", era: "1970s" },
  // 1980s
  { song: "Back In Black", artist: "AC/DC", era: "1980s" },
  { song: "Billie Jean", artist: "Michael Jackson", era: "1980s" },
  { song: "Thriller", artist: "Michael Jackson", era: "1980s" },
  { song: "Beat It", artist: "Michael Jackson", era: "1980s" },
  { song: "Smooth Criminal", artist: "Michael Jackson", era: "1980s" },
  { song: "Sweet Child O' Mine", artist: "Guns N' Roses", era: "1980s" },
  { song: "November Rain", artist: "Guns N' Roses", era: "1980s" },
  { song: "Welcome to the Jungle", artist: "Guns N' Roses", era: "1980s" },
  { song: "Livin' on a Prayer", artist: "Bon Jovi", era: "1980s" },
  { song: "Take On Me", artist: "a-ha", era: "1980s" },
  { song: "Like a Prayer", artist: "Madonna", era: "1980s" },
  { song: "Material Girl", artist: "Madonna", era: "1980s" },
  { song: "I Wanna Dance with Somebody", artist: "Whitney Houston", era: "1980s" },
  { song: "Every Breath You Take", artist: "The Police", era: "1980s" },
  { song: "With or Without You", artist: "U2", era: "1980s" },
  { song: "Sweet Dreams", artist: "Eurythmics", era: "1980s" },
  { song: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", era: "1980s" },
  { song: "Time After Time", artist: "Cyndi Lauper", era: "1980s" },
  { song: "Careless Whisper", artist: "George Michael", era: "1980s" },
  { song: "Never Gonna Give You Up", artist: "Rick Astley", era: "1980s" },
  { song: "Africa", artist: "Toto", era: "1980s" },
  { song: "Don't Stop Believin'", artist: "Journey", era: "1980s" },
  { song: "Eye of the Tiger", artist: "Survivor", era: "1980s" },
  { song: "Flashdance... What a Feeling", artist: "Irene Cara", era: "1980s" },
  { song: "Girls on Film", artist: "Duran Duran", era: "1980s" },
  { song: "Tainted Love", artist: "Soft Cell", era: "1980s" },
  { song: "Blue Monday", artist: "New Order", era: "1980s" },
  { song: "Love Will Tear Us Apart", artist: "Joy Division", era: "1980s" },
  { song: "Under Pressure", artist: "Queen", era: "1980s" },
  { song: "Another One Bites the Dust", artist: "Queen", era: "1980s" },
  { song: "Every Little Thing She Does Is Magic", artist: "The Police", era: "1980s" },
  { song: "Karma Chameleon", artist: "Culture Club", era: "1980s" },
  { song: "The Final Countdown", artist: "Europe", era: "1980s" },
  { song: "Jump", artist: "Van Halen", era: "1980s" },
  { song: "Pour Some Sugar on Me", artist: "Def Leppard", era: "1980s" },
  { song: "Livin' Thing", artist: "Electric Light Orchestra", era: "1980s" },
  { song: "Take My Breath Away", artist: "Berlin", era: "1980s" },
  { song: "Walking on Sunshine", artist: "Katrina and the Waves", era: "1980s" },
  // 1990s
  { song: "Enter Sandman", artist: "Metallica", era: "1990s" },
  { song: "Smells Like Teen Spirit", artist: "Nirvana", era: "1990s" },
  { song: "Come As You Are", artist: "Nirvana", era: "1990s" },
  { song: "Creep", artist: "Radiohead", era: "1990s" },
  { song: "Wonderwall", artist: "Oasis", era: "1990s" },
  { song: "Don't Look Back in Anger", artist: "Oasis", era: "1990s" },
  { song: "Wannabe", artist: "Spice Girls", era: "1990s" },
  { song: "No Scrubs", artist: "TLC", era: "1990s" },
  { song: "Say My Name", artist: "Destiny's Child", era: "1990s" },
  { song: "I Will Always Love You", artist: "Whitney Houston", era: "1990s" },
  { song: "Losing My Religion", artist: "R.E.M.", era: "1990s" },
  { song: "Killing in the Name", artist: "Rage Against the Machine", era: "1990s" },
  { song: "Zombie", artist: "The Cranberries", era: "1990s" },
  { song: "Nothing Else Matters", artist: "Metallica", era: "1990s" },
  { song: "Californication", artist: "Red Hot Chili Peppers", era: "1990s" },
  { song: "Under the Bridge", artist: "Red Hot Chili Peppers", era: "1990s" },
  { song: "Black Hole Sun", artist: "Soundgarden", era: "1990s" },
  { song: "Bitter Sweet Symphony", artist: "The Verve", era: "1990s" },
  { song: "Common People", artist: "Pulp", era: "1990s" },
  { song: "Baby One More Time", artist: "Britney Spears", era: "1990s" },
  { song: "I Want It That Way", artist: "Backstreet Boys", era: "1990s" },
  { song: "Everybody", artist: "Backstreet Boys", era: "1990s" },
  { song: "Bye Bye Bye", artist: "NSYNC", era: "1990s" },
  { song: "Genie in a Bottle", artist: "Christina Aguilera", era: "1990s" },
  { song: "Macarena", artist: "Los del Río", era: "1990s" },
  { song: "Gangsta's Paradise", artist: "Coolio", era: "1990s" },
  { song: "Ice Ice Baby", artist: "Vanilla Ice", era: "1990s" },
  { song: "Barbie Girl", artist: "Aqua", era: "1990s" },
  { song: "Blue (Da Ba Dee)", artist: "Eiffel 65", era: "1990s" },
  { song: "Scar Tissue", artist: "Red Hot Chili Peppers", era: "1990s" },
  { song: "Bulls on Parade", artist: "Rage Against the Machine", era: "1990s" },
  { song: "Champagne Supernova", artist: "Oasis", era: "1990s" },
  { song: "Firestarter", artist: "The Prodigy", era: "1990s" },
  { song: "Around the World", artist: "Daft Punk", era: "1990s" },
  // 2000s
  { song: "Lose Yourself", artist: "Eminem", era: "2000s" },
  { song: "Without Me", artist: "Eminem", era: "2000s" },
  { song: "In Da Club", artist: "50 Cent", era: "2000s" },
  { song: "Hey Ya!", artist: "OutKast", era: "2000s" },
  { song: "Crazy in Love", artist: "Beyoncé", era: "2000s" },
  { song: "Halo", artist: "Beyoncé", era: "2000s" },
  { song: "Umbrella", artist: "Rihanna", era: "2000s" },
  { song: "I Gotta Feeling", artist: "Black Eyed Peas", era: "2000s" },
  { song: "Poker Face", artist: "Lady Gaga", era: "2000s" },
  { song: "Bad Romance", artist: "Lady Gaga", era: "2000s" },
  { song: "Viva la Vida", artist: "Coldplay", era: "2000s" },
  { song: "Clocks", artist: "Coldplay", era: "2000s" },
  { song: "Fix You", artist: "Coldplay", era: "2000s" },
  { song: "The Scientist", artist: "Coldplay", era: "2000s" },
  { song: "Yellow", artist: "Coldplay", era: "2000s" },
  { song: "Chasing Cars", artist: "Snow Patrol", era: "2000s" },
  { song: "Mr. Brightside", artist: "The Killers", era: "2000s" },
  { song: "Somebody Told Me", artist: "The Killers", era: "2000s" },
  { song: "Seven Nation Army", artist: "The White Stripes", era: "2000s" },
  { song: "Take Me Out", artist: "Franz Ferdinand", era: "2000s" },
  { song: "Numb", artist: "Linkin Park", era: "2000s" },
  { song: "In the End", artist: "Linkin Park", era: "2000s" },
  { song: "Boulevard of Broken Dreams", artist: "Green Day", era: "2000s" },
  { song: "American Idiot", artist: "Green Day", era: "2000s" },
  { song: "Dani California", artist: "Red Hot Chili Peppers", era: "2000s" },
  { song: "Sex on Fire", artist: "Kings of Leon", era: "2000s" },
  { song: "Use Somebody", artist: "Kings of Leon", era: "2000s" },
  { song: "I'm Yours", artist: "Jason Mraz", era: "2000s" },
  { song: "Bubbly", artist: "Colbie Caillat", era: "2000s" },
  { song: "Love Story", artist: "Taylor Swift", era: "2000s" },
  { song: "You Belong With Me", artist: "Taylor Swift", era: "2000s" },
  { song: "Tik Tok", artist: "Kesha", era: "2000s" },
  { song: "Paparazzi", artist: "Lady Gaga", era: "2000s" },
  { song: "Hot N Cold", artist: "Katy Perry", era: "2000s" },
  { song: "I Kissed a Girl", artist: "Katy Perry", era: "2000s" },
  { song: "Rehab", artist: "Amy Winehouse", era: "2000s" },
  { song: "Back to Black", artist: "Amy Winehouse", era: "2000s" },
  { song: "Stronger", artist: "Kanye West", era: "2000s" },
  { song: "Gold Digger", artist: "Kanye West", era: "2000s" },
  { song: "Crank That", artist: "Soulja Boy", era: "2000s" },
  { song: "Low", artist: "Flo Rida", era: "2000s" },
  { song: "Right Round", artist: "Flo Rida", era: "2000s" },
  { song: "Beautiful Day", artist: "U2", era: "2000s" },
  { song: "Chasing the Sun", artist: "The Wanted", era: "2000s" },
  // 2010s
  { song: "Rolling in the Deep", artist: "Adele", era: "2010s" },
  { song: "Someone Like You", artist: "Adele", era: "2010s" },
  { song: "Set Fire to the Rain", artist: "Adele", era: "2010s" },
  { song: "Hello", artist: "Adele", era: "2010s" },
  { song: "Shape of You", artist: "Ed Sheeran", era: "2010s" },
  { song: "Perfect", artist: "Ed Sheeran", era: "2010s" },
  { song: "Thinking Out Loud", artist: "Ed Sheeran", era: "2010s" },
  { song: "Photograph", artist: "Ed Sheeran", era: "2010s" },
  { song: "Castle on the Hill", artist: "Ed Sheeran", era: "2010s" },
  { song: "Uptown Funk", artist: "Mark Ronson", era: "2010s" },
  { song: "Happy", artist: "Pharrell Williams", era: "2010s" },
  { song: "Get Lucky", artist: "Daft Punk", era: "2010s" },
  { song: "Counting Stars", artist: "OneRepublic", era: "2010s" },
  { song: "Believer", artist: "Imagine Dragons", era: "2010s" },
  { song: "Radioactive", artist: "Imagine Dragons", era: "2010s" },
  { song: "Demons", artist: "Imagine Dragons", era: "2010s" },
  { song: "Thunder", artist: "Imagine Dragons", era: "2010s" },
  { song: "Roar", artist: "Katy Perry", era: "2010s" },
  { song: "Firework", artist: "Katy Perry", era: "2010s" },
  { song: "Dark Horse", artist: "Katy Perry", era: "2010s" },
  { song: "Blank Space", artist: "Taylor Swift", era: "2010s" },
  { song: "Shake It Off", artist: "Taylor Swift", era: "2010s" },
  { song: "Style", artist: "Taylor Swift", era: "2010s" },
  { song: "Bad Blood", artist: "Taylor Swift", era: "2010s" },
  { song: "All of Me", artist: "John Legend", era: "2010s" },
  { song: "Stay With Me", artist: "Sam Smith", era: "2010s" },
  { song: "Take Me to Church", artist: "Hozier", era: "2010s" },
  { song: "Pompeii", artist: "Bastille", era: "2010s" },
  { song: "Rather Be", artist: "Clean Bandit", era: "2010s" },
  { song: "Lean On", artist: "Major Lazer", era: "2010s" },
  { song: "Faded", artist: "Alan Walker", era: "2010s" },
  { song: "Wake Me Up", artist: "Avicii", era: "2010s" },
  { song: "Levels", artist: "Avicii", era: "2010s" },
  { song: "Titanium", artist: "David Guetta", era: "2010s" },
  { song: "Despacito", artist: "Luis Fonsi", era: "2010s" },
  { song: "Gangnam Style", artist: "PSY", era: "2010s" },
  { song: "Sorry", artist: "Justin Bieber", era: "2010s" },
  { song: "Baby", artist: "Justin Bieber", era: "2010s" },
  { song: "Love Yourself", artist: "Justin Bieber", era: "2010s" },
  { song: "See You Again", artist: "Wiz Khalifa", era: "2010s" },
  { song: "Attention", artist: "Charlie Puth", era: "2010s" },
  { song: "Sugar", artist: "Maroon 5", era: "2010s" },
  { song: "Memories", artist: "Maroon 5", era: "2010s" },
  { song: "Payphone", artist: "Maroon 5", era: "2010s" },
  { song: "Moves Like Jagger", artist: "Maroon 5", era: "2010s" },
  { song: "Señorita", artist: "Shawn Mendes", era: "2010s" },
  { song: "Treat You Better", artist: "Shawn Mendes", era: "2010s" },
  { song: "Don't Start Now", artist: "Dua Lipa", era: "2010s" },
  { song: "One Kiss", artist: "Dua Lipa", era: "2010s" },
  { song: "New Rules", artist: "Dua Lipa", era: "2010s" },
  { song: "Starboy", artist: "The Weeknd", era: "2010s" },
  { song: "Bad Guy", artist: "Billie Eilish", era: "2010s" },
  { song: "Old Town Road", artist: "Lil Nas X", era: "2010s" },
  { song: "Sweet but Psycho", artist: "Ava Max", era: "2010s" },
  { song: "Happier", artist: "Marshmello", era: "2010s" },
  { song: "God's Plan", artist: "Drake", era: "2010s" },
  { song: "Hotline Bling", artist: "Drake", era: "2010s" },
  { song: "In My Feelings", artist: "Drake", era: "2010s" },
  { song: "Closer", artist: "The Chainsmokers", era: "2010s" },
  { song: "Something Just Like This", artist: "The Chainsmokers", era: "2010s" },
  { song: "Cheap Thrills", artist: "Sia", era: "2010s" },
  { song: "Chandelier", artist: "Sia", era: "2010s" },
  { song: "Royals", artist: "Lorde", era: "2010s" },
  { song: "Riptide", artist: "Vance Joy", era: "2010s" },
  { song: "Ho Hey", artist: "The Lumineers", era: "2010s" },
  { song: "Little Talks", artist: "Of Monsters and Men", era: "2010s" },
  { song: "Let Her Go", artist: "Passenger", era: "2010s" },
  { song: "Budapest", artist: "George Ezra", era: "2010s" },
  { song: "Rude", artist: "Magic!", era: "2010s" },
  { song: "Cake by the Ocean", artist: "DNCE", era: "2010s" },
  { song: "Can't Stop the Feeling!", artist: "Justin Timberlake", era: "2010s" },
  { song: "Locked Away", artist: "R. City", era: "2010s" },
  { song: "Let Me Love You", artist: "DJ Snake", era: "2010s" },
  { song: "Turn Down for What", artist: "DJ Snake", era: "2010s" },
  { song: "Mmm Whatcha Say", artist: "Jason Derulo", era: "2010s" },
  { song: "Talk Dirty", artist: "Jason Derulo", era: "2010s" },
  { song: "Wiggle", artist: "Jason Derulo", era: "2010s" },
  { song: "Trap Queen", artist: "Fetty Wap", era: "2010s" },
  { song: "Black Beatles", artist: "Rae Sremmurd", era: "2010s" },
  { song: "Bad and Boujee", artist: "Migos", era: "2010s" },
  { song: "Havana", artist: "Camila Cabello", era: "2010s" },
  { song: "Body Like a Back Road", artist: "Sam Hunt", era: "2010s" },
  { song: "Meant to Be", artist: "Bebe Rexha", era: "2010s" },
  { song: "Girls Like You", artist: "Maroon 5", era: "2010s" },
  // 2020s
  { song: "Levitating", artist: "Dua Lipa", era: "2020s" },
  { song: "Blinding Lights", artist: "The Weeknd", era: "2020s" },
  { song: "Save Your Tears", artist: "The Weeknd", era: "2020s" },
  { song: "Stay", artist: "The Kid LAROI", era: "2020s" },
  { song: "Flowers", artist: "Miley Cyrus", era: "2020s" },
  { song: "As It Was", artist: "Harry Styles", era: "2020s" },
  { song: "Watermelon Sugar", artist: "Harry Styles", era: "2020s" },
  { song: "Drivers License", artist: "Olivia Rodrigo", era: "2020s" },
  { song: "Good 4 U", artist: "Olivia Rodrigo", era: "2020s" },
  { song: "Anti-Hero", artist: "Taylor Swift", era: "2020s" },
  { song: "Cruel Summer", artist: "Taylor Swift", era: "2020s" },
  { song: "Fortnight", artist: "Taylor Swift", era: "2020s" },
  { song: "Espresso", artist: "Sabrina Carpenter", era: "2020s" },
  { song: "Please Please Please", artist: "Sabrina Carpenter", era: "2020s" },
  { song: "Die With A Smile", artist: "Lady Gaga", era: "2020s" },
  { song: "Ordinary", artist: "Alex Warren", era: "2020s" },
  { song: "Golden", artist: "HUNTR/X", era: "2020s" },
  { song: "APT.", artist: "Rosé", era: "2020s" },
  { song: "Birds of a Feather", artist: "Billie Eilish", era: "2020s" },
  { song: "Lunch", artist: "Billie Eilish", era: "2020s" },
  { song: "Too Sweet", artist: "Hozier", era: "2020s" },
  { song: "Beautiful Things", artist: "Benson Boone", era: "2020s" },
  { song: "Stick Season", artist: "Noah Kahan", era: "2020s" },
  { song: "Sunflower", artist: "Post Malone", era: "2020s" },
  { song: "Circles", artist: "Post Malone", era: "2020s" },
  { song: "Rockstar", artist: "DaBaby", era: "2020s" },
  { song: "Savage Love", artist: "Jawsh 685", era: "2020s" },
  { song: "Wellerman", artist: "Nathan Evans", era: "2020s" },
  { song: "Glimpse of Us", artist: "Joji", era: "2020s" },
  { song: "Heat Waves", artist: "Glass Animals", era: "2020s" },
];

module.exports = { SONGS };
