// ============================================
// LOGO POOL v2 (2026-09-27) - 500+ curated brand logos
// ============================================
// Owner brief section 1: expand to 500+, keep it RECOGNIZABLE (modern brands,
// apps, websites, companies, games, platforms + iconic older logos), no
// obscure/obsolete filler. Each entry anchors a Wikipedia File-namespace
// search: { name } is displayed, { wiki } is the search/anchor string
// (article-style title), { cat } drives fair same-category distractors.
//
// Curation rules used:
//   - every brand must be globally recognizable to a casual WhatsApp user
//   - modern-first but with deliberately iconic classics (Coca-Cola, Disney...)
//   - file search must plausibly find "<brand> logo" on Wikipedia - brands
//     with no logo article presence were excluded, not padded with
// - ============================================

// ---------- Tech & Software ----------
const TECH = [
  { name: "Apple", wiki: "Apple Inc.", cat: "Tech" },
  { name: "Microsoft", wiki: "Microsoft", cat: "Tech" },
  { name: "Google", wiki: "Google", cat: "Tech" },
  { name: "Amazon", wiki: "Amazon (company)", cat: "Tech" },
  { name: "Meta", wiki: "Meta Platforms", cat: "Tech" },
  { name: "IBM", wiki: "IBM", cat: "Tech" },
  { name: "Intel", wiki: "Intel", cat: "Tech" },
  { name: "AMD", wiki: "AMD", cat: "Tech" },
  { name: "Nvidia", wiki: "Nvidia", cat: "Tech" },
  { name: "Samsung", wiki: "Samsung Electronics", cat: "Tech" },
  { name: "Sony", wiki: "Sony", cat: "Tech" },
  { name: "Panasonic", wiki: "Panasonic", cat: "Tech" },
  { name: "Lenovo", wiki: "Lenovo", cat: "Tech" },
  { name: "Dell", wiki: "Dell", cat: "Tech" },
  { name: "Adobe", wiki: "Adobe Inc.", cat: "Tech" },
  { name: "Oracle", wiki: "Oracle Corporation", cat: "Tech" },
  { name: "Cisco", wiki: "Cisco", cat: "Tech" },
  { name: "HP", wiki: "HP Inc.", cat: "Tech" },
  { name: "Xiaomi", wiki: "Xiaomi", cat: "Tech" },
  { name: "Huawei", wiki: "Huawei", cat: "Tech" },
  { name: "Asus", wiki: "Asus", cat: "Tech" },
  { name: "Acer", wiki: "Acer Inc.", cat: "Tech" },
  { name: "MSI", wiki: "Micro-Star International", cat: "Tech" },
  { name: "Razer", wiki: "Razer Inc.", cat: "Tech" },
  { name: "Logitech", wiki: "Logitech", cat: "Tech" },
  { name: "Seagate", wiki: "Seagate Technology", cat: "Tech" },
  { name: "Kingston", wiki: "Kingston Technology", cat: "Tech" },
  { name: "OpenAI", wiki: "OpenAI", cat: "Tech" },
  { name: "Salesforce", wiki: "Salesforce", cat: "Tech" },
  { name: "SAP", wiki: "SAP", cat: "Tech" },
  { name: "Zoom", wiki: "Zoom (software)", cat: "Tech" },
  { name: "Slack", wiki: "Slack (software)", cat: "Tech" },
  { name: "Dropbox", wiki: "Dropbox", cat: "Tech" },
  { name: "GitHub", wiki: "GitHub", cat: "Tech" },
  { name: "Mozilla Firefox", wiki: "Firefox", cat: "Tech" },
  { name: "Google Chrome", wiki: "Google Chrome", cat: "Tech" },
  { name: "Android", wiki: "Android (operating system)", cat: "Tech" },
  { name: "Windows", wiki: "Microsoft Windows", cat: "Tech" },
  { name: "Linux", wiki: "Linux", cat: "Tech" },
  { name: "Ubuntu", wiki: "Ubuntu", cat: "Tech" },
  { name: "Bluetooth", wiki: "Bluetooth", cat: "Tech" },
  { name: "Wi-Fi", wiki: "Wi-Fi", cat: "Tech" },
  { name: "USB", wiki: "USB", cat: "Tech" },
  { name: "HDMI", wiki: "HDMI", cat: "Tech" },
  { name: "Dolby", wiki: "Dolby Laboratories", cat: "Tech" },
  { name: "Qualcomm", wiki: "Qualcomm", cat: "Tech" },
  { name: "Arm", wiki: "Arm Holdings", cat: "Tech" },
  { name: "Texas Instruments", wiki: "Texas Instruments", cat: "Tech" },
  { name: "Philips", wiki: "Philips", cat: "Tech" },
  { name: "Ericsson", wiki: "Ericsson", cat: "Tech" },
  { name: "Nokia", wiki: "Nokia", cat: "Tech" },
  { name: "Motorola", wiki: "Motorola", cat: "Tech" },
  { name: "Siemens", wiki: "Siemens", cat: "Tech" },
  { name: "Toshiba", wiki: "Toshiba", cat: "Tech" },
  { name: "Sharp", wiki: "Sharp Corporation", cat: "Tech" },
  { name: "LG", wiki: "LG Corporation", cat: "Tech" },
  { name: "Casio", wiki: "Casio", cat: "Tech" },
  { name: "GoPro", wiki: "GoPro", cat: "Tech" },
  { name: "DJI", wiki: "DJI", cat: "Tech" },
  { name: "Garmin", wiki: "Garmin", cat: "Tech" },
  { name: "Fitbit", wiki: "Fitbit", cat: "Tech" },
  { name: "eBay", wiki: "eBay", cat: "Tech" },
  { name: "Yahoo!", wiki: "Yahoo!", cat: "Tech" },
  { name: "Bing", wiki: "Microsoft Bing", cat: "Tech" },
  { name: "Wikipedia", wiki: "Wikipedia", cat: "Tech" },
  { name: "Cloudflare", wiki: "Cloudflare", cat: "Tech" },
  { name: "Spotify", wiki: "Spotify", cat: "Tech" },
  { name: "Palantir", wiki: "Palantir Technologies", cat: "Tech" },
  { name: "Alibaba", wiki: "Alibaba Group", cat: "Tech" },
  { name: "Tencent", wiki: "Tencent", cat: "Tech" },
  { name: "Baidu", wiki: "Baidu", cat: "Tech" },
];

// ---------- Apps & Social ----------
const APPS = [
  { name: "Instagram", wiki: "Instagram", cat: "Apps & Social" },
  { name: "WhatsApp", wiki: "WhatsApp", cat: "Apps & Social" },
  { name: "TikTok", wiki: "TikTok", cat: "Apps & Social" },
  { name: "Snapchat", wiki: "Snapchat", cat: "Apps & Social" },
  { name: "Twitter", wiki: "Twitter", cat: "Apps & Social" },
  { name: "X", wiki: "X (social network)", cat: "Apps & Social" },
  { name: "YouTube", wiki: "YouTube", cat: "Apps & Social" },
  { name: "Netflix", wiki: "Netflix", cat: "Apps & Social" },
  { name: "Facebook", wiki: "Facebook", cat: "Apps & Social" },
  { name: "Messenger", wiki: "Messenger (software)", cat: "Apps & Social" },
  { name: "Discord", wiki: "Discord", cat: "Apps & Social" },
  { name: "Twitch", wiki: "Twitch (service)", cat: "Apps & Social" },
  { name: "Telegram", wiki: "Telegram (software)", cat: "Apps & Social" },
  { name: "Signal", wiki: "Signal (software)", cat: "Apps & Social" },
  { name: "Pinterest", wiki: "Pinterest", cat: "Apps & Social" },
  { name: "LinkedIn", wiki: "LinkedIn", cat: "Apps & Social" },
  { name: "Reddit", wiki: "Reddit", cat: "Apps & Social" },
  { name: "Skype", wiki: "Skype", cat: "Apps & Social" },
  { name: "Viber", wiki: "Viber", cat: "Apps & Social" },
  { name: "WeChat", wiki: "WeChat", cat: "Apps & Social" },
  { name: "Line", wiki: "Line (software)", cat: "Apps & Social" },
  { name: "KakaoTalk", wiki: "KakaoTalk", cat: "Apps & Social" },
  { name: "Shazam", wiki: "Shazam (application)", cat: "Apps & Social" },
  { name: "PayPal", wiki: "PayPal", cat: "Apps & Social" },
  { name: "Venmo", wiki: "Venmo", cat: "Apps & Social" },
  { name: "Cash App", wiki: "Cash App", cat: "Apps & Social" },
  { name: "Duolingo", wiki: "Duolingo", cat: "Apps & Social" },
  { name: "Shopee", wiki: "Shopee", cat: "Apps & Social" },
  { name: "Uber", wiki: "Uber", cat: "Apps & Social" },
  { name: "Lyft", wiki: "Lyft", cat: "Apps & Social" },
  { name: "Bolt", wiki: "Bolt (company)", cat: "Apps & Social" },
  { name: "Grab", wiki: "Grab Holdings", cat: "Apps & Social" },
  { name: "Airbnb", wiki: "Airbnb", cat: "Apps & Social" },
  { name: "Booking.com", wiki: "Booking.com", cat: "Apps & Social" },
  { name: "Tripadvisor", wiki: "Tripadvisor", cat: "Apps & Social" },
  { name: "Deliveroo", wiki: "Deliveroo", cat: "Apps & Social" },
  { name: "DoorDash", wiki: "DoorDash", cat: "Apps & Social" },
  { name: "Zomato", wiki: "Zomato", cat: "Apps & Social" },
  { name: "Spotify Podcasts", wiki: "Spotify", cat: "Apps & Social" },
  { name: "Chrome Remote Desktop", wiki: "Google Chrome", cat: "Apps & Social" },
  { name: "Gmail", wiki: "Gmail", cat: "Apps & Social" },
  { name: "Google Maps", wiki: "Google Maps", cat: "Apps & Social" },
  { name: "Google Drive", wiki: "Google Drive", cat: "Apps & Social" },
  { name: "Google Play", wiki: "Google Play", cat: "Apps & Social" },
  { name: "App Store", wiki: "App Store (Apple)", cat: "Apps & Social" },
  { name: "Apple Music", wiki: "Apple Music", cat: "Apps & Social" },
  { name: "Apple Pay", wiki: "Apple Pay", cat: "Apps & Social" },
  { name: "iCloud", wiki: "ICloud", cat: "Apps & Social" },
  { name: "Threads", wiki: "Threads (social network)", cat: "Apps & Social" },
  { name: "Vimeo", wiki: "Vimeo", cat: "Apps & Social" },
  { name: "Tinder", wiki: "Tinder (app)", cat: "Apps & Social" },
  { name: "Bumble", wiki: "Bumble (app)", cat: "Apps & Social" },
  { name: "OnlyFans", wiki: "OnlyFans", cat: "Apps & Social" },
];

// ---------- Food & Drink ----------
const FOOD = [
  { name: "McDonald's", wiki: "McDonald's", cat: "Food & Drink" },
  { name: "Burger King", wiki: "Burger King", cat: "Food & Drink" },
  { name: "KFC", wiki: "KFC", cat: "Food & Drink" },
  { name: "Subway", wiki: "Subway (restaurant)", cat: "Food & Drink" },
  { name: "Starbucks", wiki: "Starbucks", cat: "Food & Drink" },
  { name: "Coca-Cola", wiki: "Coca-Cola", cat: "Food & Drink" },
  { name: "Pepsi", wiki: "Pepsi", cat: "Food & Drink" },
  { name: "Red Bull", wiki: "Red Bull", cat: "Food & Drink" },
  { name: "Monster Energy", wiki: "Monster Energy", cat: "Food & Drink" },
  { name: "Heineken", wiki: "Heineken", cat: "Food & Drink" },
  { name: "Oreo", wiki: "Oreo", cat: "Food & Drink" },
  { name: "Pringles", wiki: "Pringles", cat: "Food & Drink" },
  { name: "Nutella", wiki: "Nutella", cat: "Food & Drink" },
  { name: "Pizza Hut", wiki: "Pizza Hut", cat: "Food & Drink" },
  { name: "Domino's", wiki: "Domino's Pizza", cat: "Food & Drink" },
  { name: "Krispy Kreme", wiki: "Krispy Kreme", cat: "Food & Drink" },
  { name: "Lay's", wiki: "Lay's", cat: "Food & Drink" },
  { name: "Kit Kat", wiki: "Kit Kat", cat: "Food & Drink" },
  { name: "Snickers", wiki: "Snickers (chocolate bar)", cat: "Food & Drink" },
  { name: "Nespresso", wiki: "Nespresso", cat: "Food & Drink" },
  { name: "Wendy's", wiki: "Wendy's", cat: "Food & Drink" },
  { name: "Chick-fil-A", wiki: "Chick-fil-A", cat: "Food & Drink" },
  { name: "Popeyes", wiki: "Popeyes", cat: "Food & Drink" },
  { name: "Taco Bell", wiki: "Taco Bell", cat: "Food & Drink" },
  { name: "Dunkin'", wiki: "Dunkin' Donuts", cat: "Food & Drink" },
  { name: "Baskin-Robbins", wiki: "Baskin-Robbins", cat: "Food & Drink" },
  { name: "Ben & Jerry's", wiki: "Ben & Jerry's", cat: "Food & Drink" },
  { name: "Costa Coffee", wiki: "Costa Coffee", cat: "Food & Drink" },
  { name: "Tim Hortons", wiki: "Tim Hortons", cat: "Food & Drink" },
  { name: "Dairy Queen", wiki: "Dairy Queen", cat: "Food & Drink" },
  { name: "Five Guys", wiki: "Five Guys", cat: "Food & Drink" },
  { name: "Papa John's", wiki: "Papa John's", cat: "Food & Drink" },
  { name: "Little Caesars", wiki: "Little Caesars", cat: "Food & Drink" },
  { name: "Chupa Chups", wiki: "Chupa Chups", cat: "Food & Drink" },
  { name: "Mars", wiki: "Mars, Incorporated", cat: "Food & Drink" },
  { name: "M&M's", wiki: "M&M's", cat: "Food & Drink" },
  { name: "Twix", wiki: "Twix", cat: "Food & Drink" },
  { name: "Bounty", wiki: "Bounty (chocolate bar)", cat: "Food & Drink" },
  { name: "Milky Way", wiki: "Milky Way (chocolate bar)", cat: "Food & Drink" },
  { name: "Hershey's", wiki: "The Hershey Company", cat: "Food & Drink" },
  { name: "Cadbury", wiki: "Cadbury", cat: "Food & Drink" },
  { name: "Ferrero Rocher", wiki: "Ferrero Rocher", cat: "Food & Drink" },
  { name: "Kinder", wiki: "Kinder Chocolate", cat: "Food & Drink" },
  { name: "Toblerone", wiki: "Toblerone", cat: "Food & Drink" },
  { name: "Lindt", wiki: "Lindt & Sprüngli", cat: "Food & Drink" },
  { name: "Haribo", wiki: "Haribo", cat: "Food & Drink" },
  { name: "Doritos", wiki: "Doritos", cat: "Food & Drink" },
  { name: "Cheetos", wiki: "Cheetos", cat: "Food & Drink" },
  { name: "Takis", wiki: "Takis (snack)", cat: "Food & Drink" },
  { name: "Kellogg's", wiki: "Kellanova", cat: "Food & Drink" },
  { name: "Cheerios", wiki: "Cheerios", cat: "Food & Drink" },
  { name: "Froot Loops", wiki: "Froot Loops", cat: "Food & Drink" },
  { name: "Quaker", wiki: "Quaker Oats Company", cat: "Food & Drink" },
  { name: "Nescafé", wiki: "Nescafé", cat: "Food & Drink" },
  { name: "Lavazza", wiki: "Lavazza", cat: "Food & Drink" },
  { name: "Illy", wiki: "Illy", cat: "Food & Drink" },
  { name: "Lipton", wiki: "Lipton", cat: "Food & Drink" },
  { name: "Tetley", wiki: "Tetley", cat: "Food & Drink" },
  { name: "Fanta", wiki: "Fanta", cat: "Food & Drink" },
  { name: "Sprite", wiki: "Sprite (drink)", cat: "Food & Drink" },
  { name: "Dr Pepper", wiki: "Dr Pepper", cat: "Food & Drink" },
  { name: "Mountain Dew", wiki: "Mountain Dew", cat: "Food & Drink" },
  { name: "7 Up", wiki: "7 Up", cat: "Food & Drink" },
  { name: "Mirinda", wiki: "Mirinda", cat: "Food & Drink" },
  { name: "Gatorade", wiki: "Gatorade", cat: "Food & Drink" },
  { name: "Powerade", wiki: "Powerade", cat: "Food & Drink" },
  { name: "Tropicana", wiki: "Tropicana Products", cat: "Food & Drink" },
  { name: "Lactel", wiki: "Lactalis", cat: "Food & Drink" },
  { name: "Danone", wiki: "Danone", cat: "Food & Drink" },
  { name: "Yoplait", wiki: "Yoplait", cat: "Food & Drink" },
  { name: "Chobani", wiki: "Chobani", cat: "Food & Drink" },
  { name: "Barilla", wiki: "Barilla (company)", cat: "Food & Drink" },
  { name: "Heinz", wiki: "Heinz", cat: "Food & Drink" },
  { name: "Hellmann's", wiki: "Hellmann's", cat: "Food & Drink" },
  { name: "Campbell's", wiki: "Campbell Soup Company", cat: "Food & Drink" },
  { name: "Knorr", wiki: "Knorr", cat: "Food & Drink" },
  { name: "Maggi", wiki: "Maggi", cat: "Food & Drink" },
  { name: "Uncle Ben's", wiki: "Uncle Ben's", cat: "Food & Drink" },
  { name: "Walkers", wiki: "Walkers (snack foods)", cat: "Food & Drink" },
  { name: "Slim Jim", wiki: "Slim Jim (snack food)", cat: "Food & Drink" },
  { name: "Jack in the Box", wiki: "Jack in the Box", cat: "Food & Drink" },
  { name: "In-N-Out Burger", wiki: "In-N-Out Burger", cat: "Food & Drink" },
  { name: "Whataburger", wiki: "Whataburger", cat: "Food & Drink" },
  { name: "Culver's", wiki: "Culver's", cat: "Food & Drink" },
  { name: "Chipotle", wiki: "Chipotle Mexican Grill", cat: "Food & Drink" },
  { name: "Panera Bread", wiki: "Panera Bread", cat: "Food & Drink" },
  { name: "Bacardi", wiki: "Bacardi", cat: "Food & Drink" },
  { name: "Jack Daniel's", wiki: "Jack Daniel's", cat: "Food & Drink" },
  { name: "Johnnie Walker", wiki: "Johnnie Walker", cat: "Food & Drink" },
  { name: "Hennessy", wiki: "Hennessy", cat: "Food & Drink" },
  { name: "Smirnoff", wiki: "Smirnoff", cat: "Food & Drink" },
  { name: "Absolut", wiki: "Absolut Vodka", cat: "Food & Drink" },
  { name: "Corona", wiki: "Corona (beer)", cat: "Food & Drink" },
  { name: "Budweiser", wiki: "Budweiser", cat: "Food & Drink" },
  { name: "Bud Light", wiki: "Bud Light", cat: "Food & Drink" },
  { name: "Stella Artois", wiki: "Stella Artois", cat: "Food & Drink" },
  { name: "Guinness", wiki: "Guinness", cat: "Food & Drink" },
  { name: "Carlsberg", wiki: "Carlsberg (beer)", cat: "Food & Drink" },
  { name: "Miller Lite", wiki: "Miller Lite", cat: "Food & Drink" },
  { name: "Coors Light", wiki: "Coors Light", cat: "Food & Drink" },
  { name: "Michelob Ultra", wiki: "Michelob Ultra", cat: "Food & Drink" },
  { name: "Dos Equis", wiki: "Dos Equis", cat: "Food & Drink" },
  { name: "Modelo", wiki: "Grupo Modelo", cat: "Food & Drink" },
];

// ---------- Cars & Motors ----------
const CARS = [
  { name: "Tesla", wiki: "Tesla, Inc.", cat: "Cars" },
  { name: "Toyota", wiki: "Toyota", cat: "Cars" },
  { name: "Honda", wiki: "Honda", cat: "Cars" },
  { name: "Ford", wiki: "Ford Motor Company", cat: "Cars" },
  { name: "BMW", wiki: "BMW", cat: "Cars" },
  { name: "Mercedes-Benz", wiki: "Mercedes-Benz", cat: "Cars" },
  { name: "Audi", wiki: "Audi", cat: "Cars" },
  { name: "Volkswagen", wiki: "Volkswagen", cat: "Cars" },
  { name: "Porsche", wiki: "Porsche", cat: "Cars" },
  { name: "Ferrari", wiki: "Ferrari", cat: "Cars" },
  { name: "Lamborghini", wiki: "Lamborghini", cat: "Cars" },
  { name: "Mazda", wiki: "Mazda", cat: "Cars" },
  { name: "Nissan", wiki: "Nissan", cat: "Cars" },
  { name: "Hyundai", wiki: "Hyundai Motor Company", cat: "Cars" },
  { name: "Kia", wiki: "Kia", cat: "Cars" },
  { name: "Chevrolet", wiki: "Chevrolet", cat: "Cars" },
  { name: "Jeep", wiki: "Jeep", cat: "Cars" },
  { name: "Bugatti", wiki: "Bugatti", cat: "Cars" },
  { name: "Rolls-Royce", wiki: "Rolls-Royce Motor Cars", cat: "Cars" },
  { name: "Volvo", wiki: "Volvo Cars", cat: "Cars" },
  { name: "Mitsubishi", wiki: "Mitsubishi Motors", cat: "Cars" },
  { name: "Suzuki", wiki: "Suzuki", cat: "Cars" },
  { name: "Subaru", wiki: "Subaru", cat: "Cars" },
  { name: "Lexus", wiki: "Lexus", cat: "Cars" },
  { name: "Infiniti", wiki: "Infiniti", cat: "Cars" },
  { name: "Cadillac", wiki: "Cadillac", cat: "Cars" },
  { name: "Dodge", wiki: "Dodge", cat: "Cars" },
  { name: "Chrysler", wiki: "Chrysler", cat: "Cars" },
  { name: "GMC", wiki: "GMC", cat: "Cars" },
  { name: "Lincoln", wiki: "Lincoln Motor Company", cat: "Cars" },
  { name: "Buick", wiki: "Buick", cat: "Cars" },
  { name: "Jaguar", wiki: "Jaguar Cars", cat: "Cars" },
  { name: "Land Rover", wiki: "Land Rover", cat: "Cars" },
  { name: "Mini", wiki: "Mini (marque)", cat: "Cars" },
  { name: "Bentley", wiki: "Bentley", cat: "Cars" },
  { name: "McLaren", wiki: "McLaren Automotive", cat: "Cars" },
  { name: "Maserati", wiki: "Maserati", cat: "Cars" },
  { name: "Alfa Romeo", wiki: "Alfa Romeo", cat: "Cars" },
  { name: "Fiat", wiki: "Fiat", cat: "Cars" },
  { name: "Peugeot", wiki: "Peugeot", cat: "Cars" },
  { name: "Renault", wiki: "Renault", cat: "Cars" },
  { name: "Citroën", wiki: "Citroën", cat: "Cars" },
  { name: "Škoda", wiki: "Škoda Auto", cat: "Cars" },
  { name: "Seat", wiki: "SEAT", cat: "Cars" },
  { name: "Opel", wiki: "Opel", cat: "Cars" },
  { name: "Vauxhall", wiki: "Vauxhall Motors", cat: "Cars" },
  { name: "Aston Martin", wiki: "Aston Martin", cat: "Cars" },
  { name: "Lotus", wiki: "Lotus Cars", cat: "Cars" },
  { name: "Koenigsegg", wiki: "Koenigsegg", cat: "Cars" },
  { name: "Pagani", wiki: "Pagani (company)", cat: "Cars" },
  { name: "Rimac", wiki: "Rimac Automobili", cat: "Cars" },
  { name: "Rivian", wiki: "Rivian", cat: "Cars" },
  { name: "Lucid", wiki: "Lucid Motors", cat: "Cars" },
  { name: "Polestar", wiki: "Polestar", cat: "Cars" },
  { name: "BYD", wiki: "BYD Auto", cat: "Cars" },
  { name: "Geely", wiki: "Geely", cat: "Cars" },
  { name: "Michelin", wiki: "Michelin", cat: "Cars" },
  { name: "Goodyear", wiki: "Goodyear Tire and Rubber Company", cat: "Cars" },
  { name: "Pirelli", wiki: "Pirelli", cat: "Cars" },
  { name: "Bridgestone", wiki: "Bridgestone", cat: "Cars" },
  { name: "Shell", wiki: "Shell plc", cat: "Cars" },
  { name: "BP", wiki: "BP", cat: "Cars" },
  { name: "Castrol", wiki: "Castrol", cat: "Cars" },
];

// ---------- Fashion & Footwear ----------
const FASHION = [
  { name: "Nike", wiki: "Nike, Inc.", cat: "Fashion" },
  { name: "Adidas", wiki: "Adidas", cat: "Fashion" },
  { name: "Puma", wiki: "Puma (brand)", cat: "Fashion" },
  { name: "Reebok", wiki: "Reebok", cat: "Fashion" },
  { name: "New Balance", wiki: "New Balance", cat: "Fashion" },
  { name: "Under Armour", wiki: "Under Armour", cat: "Fashion" },
  { name: "Gucci", wiki: "Gucci", cat: "Fashion" },
  { name: "Louis Vuitton", wiki: "Louis Vuitton", cat: "Fashion" },
  { name: "Chanel", wiki: "Chanel", cat: "Fashion" },
  { name: "Prada", wiki: "Prada", cat: "Fashion" },
  { name: "Zara", wiki: "Zara (retailer)", cat: "Fashion" },
  { name: "H&M", wiki: "H&M", cat: "Fashion" },
  { name: "Uniqlo", wiki: "Uniqlo", cat: "Fashion" },
  { name: "Levi's", wiki: "Levi Strauss & Co.", cat: "Fashion" },
  { name: "Converse", wiki: "Converse (brand)", cat: "Fashion" },
  { name: "Vans", wiki: "Vans", cat: "Fashion" },
  { name: "The North Face", wiki: "The North Face", cat: "Fashion" },
  { name: "Lacoste", wiki: "Lacoste", cat: "Fashion" },
  { name: "Burberry", wiki: "Burberry", cat: "Fashion" },
  { name: "Tommy Hilfiger", wiki: "Tommy Hilfiger (brand)", cat: "Fashion" },
  { name: "Ralph Lauren", wiki: "Ralph Lauren Corporation", cat: "Fashion" },
  { name: "Calvin Klein", wiki: "Calvin Klein (brand)", cat: "Fashion" },
  { name: "Dior", wiki: "Dior", cat: "Fashion" },
  { name: "Versace", wiki: "Versace", cat: "Fashion" },
  { name: "Armani", wiki: "Armani", cat: "Fashion" },
  { name: "Dolce & Gabbana", wiki: "Dolce & Gabbana", cat: "Fashion" },
  { name: "Balenciaga", wiki: "Balenciaga", cat: "Fashion" },
  { name: "Givenchy", wiki: "Givenchy", cat: "Fashion" },
  { name: "Yves Saint Laurent", wiki: "Yves Saint Laurent (brand)", cat: "Fashion" },
  { name: "Hermès", wiki: "Hermès", cat: "Fashion" },
  { name: "Fendi", wiki: "Fendi", cat: "Fashion" },
  { name: "Miu Miu", wiki: "Miu Miu", cat: "Fashion" },
  { name: "Off-White", wiki: "Off-White (company)", cat: "Fashion" },
  { name: "Supreme", wiki: "Supreme (brand)", cat: "Fashion" },
  { name: "Champion", wiki: "Champion (sportswear)", cat: "Fashion" },
  { name: "Skechers", wiki: "Skechers", cat: "Fashion" },
  { name: "Crocs", wiki: "Crocs", cat: "Fashion" },
  { name: "Timberland", wiki: "Timberland (company)", cat: "Fashion" },
  { name: "Dr. Martens", wiki: "Dr. Martens", cat: "Fashion" },
  { name: "Salomon", wiki: "Salomon Group", cat: "Fashion" },
  { name: "Arc'teryx", wiki: "Arc'teryx", cat: "Fashion" },
  { name: "Patagonia", wiki: "Patagonia, Inc.", cat: "Fashion" },
  { name: "Columbia", wiki: "Columbia Sportswear", cat: "Fashion" },
  { name: "ASOS", wiki: "ASOS.com", cat: "Fashion" },
  { name: "Shein", wiki: "Shein", cat: "Fashion" },
  { name: "Primark", wiki: "Primark", cat: "Fashion" },
  { name: "Next", wiki: "Next plc", cat: "Fashion" },
  { name: "Gap", wiki: "Gap Inc.", cat: "Fashion" },
  { name: "Abercrombie & Fitch", wiki: "Abercrombie & Fitch", cat: "Fashion" },
  { name: "Hollister", wiki: "Hollister Co.", cat: "Fashion" },
  { name: "American Eagle", wiki: "American Eagle Outfitters", cat: "Fashion" },
  { name: "Urban Outfitters", wiki: "Urban Outfitters", cat: "Fashion" },
  { name: "Pull & Bear", wiki: "Pull&Bear", cat: "Fashion" },
  { name: "Bershka", wiki: "Bershka", cat: "Fashion" },
  { name: "Mango", wiki: "Mango (retailer)", cat: "Fashion" },
];

// ---------- Sports & Clubs ----------
const SPORTS = [
  { name: "FIFA", wiki: "FIFA", cat: "Sports" },
  { name: "UEFA Champions League", wiki: "UEFA Champions League", cat: "Sports" },
  { name: "NBA", wiki: "National Basketball Association", cat: "Sports" },
  { name: "NFL", wiki: "National Football League", cat: "Sports" },
  { name: "Formula 1", wiki: "Formula One", cat: "Sports" },
  { name: "FC Barcelona", wiki: "FC Barcelona", cat: "Sports" },
  { name: "Real Madrid", wiki: "Real Madrid CF", cat: "Sports" },
  { name: "Manchester United", wiki: "Manchester United F.C.", cat: "Sports" },
  { name: "Liverpool FC", wiki: "Liverpool F.C.", cat: "Sports" },
  { name: "Arsenal", wiki: "Arsenal F.C.", cat: "Sports" },
  { name: "Chelsea FC", wiki: "Chelsea F.C.", cat: "Sports" },
  { name: "Bayern Munich", wiki: "FC Bayern Munich", cat: "Sports" },
  { name: "Juventus", wiki: "Juventus FC", cat: "Sports" },
  { name: "Paris Saint-Germain", wiki: "Paris Saint-Germain F.C.", cat: "Sports" },
  { name: "AC Milan", wiki: "AC Milan", cat: "Sports" },
  { name: "Inter Milan", wiki: "Inter Milan", cat: "Sports" },
  { name: "Borussia Dortmund", wiki: "Borussia Dortmund", cat: "Sports" },
  { name: "Ajax", wiki: "AFC Ajax", cat: "Sports" },
  { name: "Manchester City", wiki: "Manchester City F.C.", cat: "Sports" },
  { name: "Tottenham Hotspur", wiki: "Tottenham Hotspur F.C.", cat: "Sports" },
  { name: "Premier League", wiki: "Premier League", cat: "Sports" },
  { name: "La Liga", wiki: "La Liga", cat: "Sports" },
  { name: "Serie A", wiki: "Serie A", cat: "Sports" },
  { name: "Bundesliga", wiki: "Bundesliga", cat: "Sports" },
  { name: "MLB", wiki: "Major League Baseball", cat: "Sports" },
  { name: "NHL", wiki: "National Hockey League", cat: "Sports" },
  { name: "NASCAR", wiki: "NASCAR", cat: "Sports" },
  { name: "MotoGP", wiki: "Grand Prix motorcycle racing", cat: "Sports" },
  { name: "WWE", wiki: "WWE", cat: "Sports" },
  { name: "UFC", wiki: "Ultimate Fighting Championship", cat: "Sports" },
  { name: "Olympics", wiki: "International Olympic Committee", cat: "Sports" },
  { name: "FIFA World Cup", wiki: "FIFA World Cup", cat: "Sports" },
  { name: "Super Bowl", wiki: "Super Bowl", cat: "Sports" },
  { name: "Cricket World Cup", wiki: "Cricket World Cup", cat: "Sports" },
  { name: "IPL", wiki: "Indian Premier League", cat: "Sports" },
  { name: "Tour de France", wiki: "Tour de France", cat: "Sports" },
  { name: "Wimbledon", wiki: "Wimbledon Championships", cat: "Sports" },
  { name: "Los Angeles Lakers", wiki: "Los Angeles Lakers", cat: "Sports" },
  { name: "Golden State Warriors", wiki: "Golden State Warriors", cat: "Sports" },
  { name: "Chicago Bulls", wiki: "Chicago Bulls", cat: "Sports" },
  { name: "New York Yankees", wiki: "New York Yankees", cat: "Sports" },
  { name: "Dallas Cowboys", wiki: "Dallas Cowboys", cat: "Sports" },
  { name: "Everton", wiki: "Everton F.C.", cat: "Sports" },
  { name: "Newcastle United", wiki: "Newcastle United F.C.", cat: "Sports" },
];

// ---------- Entertainment & Gaming ----------
const GAMING = [
  { name: "Disney", wiki: "The Walt Disney Company", cat: "Entertainment & Gaming" },
  { name: "Pixar", wiki: "Pixar", cat: "Entertainment & Gaming" },
  { name: "Marvel", wiki: "Marvel Entertainment", cat: "Entertainment & Gaming" },
  { name: "DC Comics", wiki: "DC Comics", cat: "Entertainment & Gaming" },
  { name: "Warner Bros.", wiki: "Warner Bros.", cat: "Entertainment & Gaming" },
  { name: "Universal Pictures", wiki: "Universal Pictures", cat: "Entertainment & Gaming" },
  { name: "Paramount", wiki: "Paramount Pictures", cat: "Entertainment & Gaming" },
  { name: "HBO", wiki: "HBO", cat: "Entertainment & Gaming" },
  { name: "MTV", wiki: "MTV", cat: "Entertainment & Gaming" },
  { name: "Cartoon Network", wiki: "Cartoon Network", cat: "Entertainment & Gaming" },
  { name: "Nickelodeon", wiki: "Nickelodeon", cat: "Entertainment & Gaming" },
  { name: "Lego", wiki: "Lego", cat: "Entertainment & Gaming" },
  { name: "Nintendo", wiki: "Nintendo", cat: "Entertainment & Gaming" },
  { name: "PlayStation", wiki: "PlayStation", cat: "Entertainment & Gaming" },
  { name: "Xbox", wiki: "Xbox", cat: "Entertainment & Gaming" },
  { name: "Sega", wiki: "Sega", cat: "Entertainment & Gaming" },
  { name: "Atari", wiki: "Atari, Inc.", cat: "Entertainment & Gaming" },
  { name: "Rockstar Games", wiki: "Rockstar Games", cat: "Entertainment & Gaming" },
  { name: "Minecraft", wiki: "Minecraft", cat: "Entertainment & Gaming" },
  { name: "Roblox", wiki: "Roblox", cat: "Entertainment & Gaming" },
  { name: "Pokémon", wiki: "Pokémon", cat: "Entertainment & Gaming" },
  { name: "Ubisoft", wiki: "Ubisoft", cat: "Entertainment & Gaming" },
  { name: "Electronic Arts", wiki: "Electronic Arts", cat: "Entertainment & Gaming" },
  { name: "Epic Games", wiki: "Epic Games", cat: "Entertainment & Gaming" },
  { name: "Steam", wiki: "Steam (service)", cat: "Entertainment & Gaming" },
  { name: "Valve", wiki: "Valve Corporation", cat: "Entertainment & Gaming" },
  { name: "Riot Games", wiki: "Riot Games", cat: "Entertainment & Gaming" },
  { name: "Blizzard Entertainment", wiki: "Blizzard Entertainment", cat: "Entertainment & Gaming" },
  { name: "Activision", wiki: "Activision", cat: "Entertainment & Gaming" },
  { name: "Bethesda", wiki: "Bethesda Softworks", cat: "Entertainment & Gaming" },
  { name: "Square Enix", wiki: "Square Enix", cat: "Entertainment & Gaming" },
  { name: "Capcom", wiki: "Capcom", cat: "Entertainment & Gaming" },
  { name: "Konami", wiki: "Konami", cat: "Entertainment & Gaming" },
  { name: "Bandai Namco", wiki: "Bandai Namco Entertainment", cat: "Entertainment & Gaming" },
  { name: "Fortnite", wiki: "Fortnite", cat: "Entertainment & Gaming" },
  { name: "Call of Duty", wiki: "Call of Duty", cat: "Entertainment & Gaming" },
  { name: "Grand Theft Auto", wiki: "Grand Theft Auto", cat: "Entertainment & Gaming" },
  { name: "The Sims", wiki: "The Sims", cat: "Entertainment & Gaming" },
  { name: "Among Us", wiki: "Among Us", cat: "Entertainment & Gaming" },
  { name: "Super Mario", wiki: "Mario (franchise)", cat: "Entertainment & Gaming" },
  { name: "The Legend of Zelda", wiki: "The Legend of Zelda", cat: "Entertainment & Gaming" },
  { name: "Sonic the Hedgehog", wiki: "Sonic the Hedgehog", cat: "Entertainment & Gaming" },
  { name: "Pac-Man", wiki: "Pac-Man", cat: "Entertainment & Gaming" },
  { name: "Tetris", wiki: "Tetris", cat: "Entertainment & Gaming" },
  { name: "Angry Birds", wiki: "Angry Birds", cat: "Entertainment & Gaming" },
  { name: "Candy Crush", wiki: "Candy Crush Saga", cat: "Entertainment & Gaming" },
  { name: "Clash of Clans", wiki: "Clash of Clans", cat: "Entertainment & Gaming" },
  { name: "DreamWorks", wiki: "DreamWorks Pictures", cat: "Entertainment & Gaming" },
  { name: "Studio Ghibli", wiki: "Studio Ghibli", cat: "Entertainment & Gaming" },
  { name: "A24", wiki: "A24", cat: "Entertainment & Gaming" },
  { name: "IMAX", wiki: "IMAX", cat: "Entertainment & Gaming" },
  { name: "20th Century Studios", wiki: "20th Century Studios", cat: "Entertainment & Gaming" },
  { name: "Columbia Pictures", wiki: "Columbia Pictures", cat: "Entertainment & Gaming" },
  { name: "MGM", wiki: "Metro-Goldwyn-Mayer", cat: "Entertainment & Gaming" },
  { name: "Lionsgate", wiki: "Lionsgate", cat: "Entertainment & Gaming" },
  { name: "StudioCanal", wiki: "StudioCanal", cat: "Entertainment & Gaming" },
  { name: "Toei Animation", wiki: "Toei Animation", cat: "Entertainment & Gaming" },
  { name: "Crunchyroll", wiki: "Crunchyroll", cat: "Entertainment & Gaming" },
  { name: "Funimation", wiki: "Funimation", cat: "Entertainment & Gaming" },
  { name: "Rotten Tomatoes", wiki: "Rotten Tomatoes", cat: "Entertainment & Gaming" },
  { name: "IMDb", wiki: "IMDb", cat: "Entertainment & Gaming" },
  { name: "GameStop", wiki: "GameStop", cat: "Entertainment & Gaming" },
  { name: "Hot Wheels", wiki: "Hot Wheels", cat: "Entertainment & Gaming" },
  { name: "Barbie", wiki: "Barbie", cat: "Entertainment & Gaming" },
  { name: "Play-Doh", wiki: "Play-Doh", cat: "Entertainment & Gaming" },
  { name: "Nerf", wiki: "Nerf", cat: "Entertainment & Gaming" },
  { name: "Funko", wiki: "Funko", cat: "Entertainment & Gaming" },
  { name: "Pop Mart", wiki: "Pop Mart", cat: "Entertainment & Gaming" },
];

// ---------- Retail & Banking ----------
const RETAIL = [
  { name: "Walmart", wiki: "Walmart", cat: "Retail & Banking" },
  { name: "IKEA", wiki: "IKEA", cat: "Retail & Banking" },
  { name: "Target", wiki: "Target Corporation", cat: "Retail & Banking" },
  { name: "Costco", wiki: "Costco", cat: "Retail & Banking" },
  { name: "Tesco", wiki: "Tesco", cat: "Retail & Banking" },
  { name: "7-Eleven", wiki: "7-Eleven", cat: "Retail & Banking" },
  { name: "Visa", wiki: "Visa Inc.", cat: "Retail & Banking" },
  { name: "Mastercard", wiki: "Mastercard", cat: "Retail & Banking" },
  { name: "American Express", wiki: "American Express", cat: "Retail & Banking" },
  { name: "HSBC", wiki: "HSBC", cat: "Retail & Banking" },
  { name: "Sainsbury's", wiki: "Sainsbury's", cat: "Retail & Banking" },
  { name: "Aldi", wiki: "Aldi", cat: "Retail & Banking" },
  { name: "Lidl", wiki: "Lidl", cat: "Retail & Banking" },
  { name: "Carrefour", wiki: "Carrefour", cat: "Retail & Banking" },
  { name: "Kroger", wiki: "Kroger", cat: "Retail & Banking" },
  { name: "Walgreens", wiki: "Walgreens", cat: "Retail & Banking" },
  { name: "CVS", wiki: "CVS Pharmacy", cat: "Retail & Banking" },
  { name: "Home Depot", wiki: "The Home Depot", cat: "Retail & Banking" },
  { name: "Lowe's", wiki: "Lowe's", cat: "Retail & Banking" },
  { name: "Best Buy", wiki: "Best Buy", cat: "Retail & Banking" },
  { name: "Macy's", wiki: "Macy's", cat: "Retail & Banking" },
  { name: "Kohl's", wiki: "Kohl's", cat: "Retail & Banking" },
  { name: "Sam's Club", wiki: "Sam's Club", cat: "Retail & Banking" },
  { name: "Dollar General", wiki: "Dollar General", cat: "Retail & Banking" },
  { name: "Tractor Supply", wiki: "Tractor Supply Company", cat: "Retail & Banking" },
  { name: "Chase", wiki: "Chase Bank", cat: "Retail & Banking" },
  { name: "Bank of America", wiki: "Bank of America", cat: "Retail & Banking" },
  { name: "Wells Fargo", wiki: "Wells Fargo", cat: "Retail & Banking" },
  { name: "Citibank", wiki: "Citibank", cat: "Retail & Banking" },
  { name: "Goldman Sachs", wiki: "Goldman Sachs", cat: "Retail & Banking" },
  { name: "Morgan Stanley", wiki: "Morgan Stanley", cat: "Retail & Banking" },
  { name: "Barclays", wiki: "Barclays", cat: "Retail & Banking" },
  { name: "Deutsche Bank", wiki: "Deutsche Bank", cat: "Retail & Banking" },
  { name: "Santander", wiki: "Santander Bank", cat: "Retail & Banking" },
  { name: "BNP Paribas", wiki: "BNP Paribas", cat: "Retail & Banking" },
  { name: "Western Union", wiki: "Western Union", cat: "Retail & Banking" },
  { name: "MoneyGram", wiki: "MoneyGram", cat: "Retail & Banking" },
];

// ---------- Airlines & Travel ----------
const TRAVEL = [
  { name: "Emirates", wiki: "Emirates (airline)", cat: "Airlines & Travel" },
  { name: "Qatar Airways", wiki: "Qatar Airways", cat: "Airlines & Travel" },
  { name: "Lufthansa", wiki: "Lufthansa", cat: "Airlines & Travel" },
  { name: "British Airways", wiki: "British Airways", cat: "Airlines & Travel" },
  { name: "Ryanair", wiki: "Ryanair", cat: "Airlines & Travel" },
  { name: "Turkish Airlines", wiki: "Turkish Airlines", cat: "Airlines & Travel" },
  { name: "Singapore Airlines", wiki: "Singapore Airlines", cat: "Airlines & Travel" },
  { name: "Delta Air Lines", wiki: "Delta Air Lines", cat: "Airlines & Travel" },
  { name: "American Airlines", wiki: "American Airlines", cat: "Airlines & Travel" },
  { name: "United Airlines", wiki: "United Airlines", cat: "Airlines & Travel" },
  { name: "Air France", wiki: "Air France", cat: "Airlines & Travel" },
  { name: "KLM", wiki: "KLM", cat: "Airlines & Travel" },
  { name: "Airbus", wiki: "Airbus", cat: "Airlines & Travel" },
  { name: "Boeing", wiki: "Boeing", cat: "Airlines & Travel" },
  { name: "EasyJet", wiki: "EasyJet", cat: "Airlines & Travel" },
  { name: "Etihad Airways", wiki: "Etihad Airways", cat: "Airlines & Travel" },
  { name: "Qantas", wiki: "Qantas", cat: "Airlines & Travel" },
  { name: "Air Canada", wiki: "Air Canada", cat: "Airlines & Travel" },
  { name: "Ethiopian Airlines", wiki: "Ethiopian Airlines", cat: "Airlines & Travel" },
  { name: "Cathay Pacific", wiki: "Cathay Pacific", cat: "Airlines & Travel" },
  { name: "Booking Holdings", wiki: "Booking Holdings", cat: "Airlines & Travel" },
];

// ---------- Media, TV & Music ----------
const MEDIA = [
  { name: "BBC", wiki: "BBC", cat: "Media & TV" },
  { name: "CNN", wiki: "CNN", cat: "Media & TV" },
  { name: "Fox", wiki: "Fox Broadcasting Company", cat: "Media & TV" },
  { name: "Sky", wiki: "Sky Group", cat: "Media & TV" },
  { name: "Al Jazeera", wiki: "Al Jazeera", cat: "Media & TV" },
  { name: "ESPN", wiki: "ESPN", cat: "Media & TV" },
  { name: "Discovery", wiki: "Warner Bros. Discovery", cat: "Media & TV" },
  { name: "National Geographic", wiki: "National Geographic", cat: "Media & TV" },
  { name: "Comedy Central", wiki: "Comedy Central", cat: "Media & TV" },
  { name: "AMC", wiki: "AMC (TV channel)", cat: "Media & TV" },
  { name: "Peacock", wiki: "Peacock (streaming service)", cat: "Media & TV" },
  { name: "Hulu", wiki: "Hulu", cat: "Media & TV" },
  { name: "Disney+", wiki: "Disney+", cat: "Media & TV" },
  { name: "HBO Max", wiki: "Max (streaming service)", cat: "Media & TV" },
  { name: "Prime Video", wiki: "Amazon Prime Video", cat: "Media & TV" },
  { name: "Apple TV+", wiki: "Apple TV+", cat: "Media & TV" },
  { name: "Paramount+", wiki: "Paramount+", cat: "Media & TV" },
  { name: "YouTube Music", wiki: "YouTube Music", cat: "Media & TV" },
  { name: "SoundCloud", wiki: "SoundCloud", cat: "Media & TV" },
  { name: "Deezer", wiki: "Deezer", cat: "Media & TV" },
  { name: "Tidal", wiki: "Tidal (service)", cat: "Media & TV" },
  { name: "Pandora", wiki: "Pandora Radio", cat: "Media & TV" },
  { name: "Audible", wiki: "Audible (service)", cat: "Media & TV" },
  { name: "Kindle", wiki: "Amazon Kindle", cat: "Media & TV" },
  { name: "Wattpad", wiki: "Wattpad", cat: "Media & TV" },
  { name: "Goodreads", wiki: "Goodreads", cat: "Media & TV" },
  { name: "Rolling Stone", wiki: "Rolling Stone", cat: "Media & TV" },
  { name: "Billboard", wiki: "Billboard (magazine)", cat: "Media & TV" },
  { name: "Forbes", wiki: "Forbes", cat: "Media & TV" },
  { name: "Reuters", wiki: "Reuters", cat: "Media & TV" },
  { name: "Bloomberg", wiki: "Bloomberg News", cat: "Media & TV" },
  { name: "The New York Times", wiki: "The New York Times", cat: "Media & TV" },
];

// ---------- Fintech & Crypto ----------
const FINTECH = [
  { name: "Bitcoin", wiki: "Bitcoin", cat: "Fintech & Crypto" },
  { name: "Ethereum", wiki: "Ethereum", cat: "Fintech & Crypto" },
  { name: "Binance", wiki: "Binance", cat: "Fintech & Crypto" },
  { name: "Coinbase", wiki: "Coinbase", cat: "Fintech & Crypto" },
  { name: "Robinhood", wiki: "Robinhood (company)", cat: "Fintech & Crypto" },
  { name: "Stripe", wiki: "Stripe, Inc.", cat: "Fintech & Crypto" },
  { name: "Klarna", wiki: "Klarna", cat: "Fintech & Crypto" },
  { name: "Revolut", wiki: "Revolut", cat: "Fintech & Crypto" },
  { name: "Wise", wiki: "Wise (company)", cat: "Fintech & Crypto" },
  { name: "Nubank", wiki: "Nubank", cat: "Fintech & Crypto" },
  { name: "Chipper Cash", wiki: "Chipper Cash", cat: "Fintech & Crypto" },
  { name: "M-Pesa", wiki: "M-Pesa", cat: "Fintech & Crypto" },
  { name: "Ripple", wiki: "Ripple Labs", cat: "Fintech & Crypto" },
  { name: "Tether", wiki: "Tether (cryptocurrency)", cat: "Fintech & Crypto" },
  { name: "Dogecoin", wiki: "Dogecoin", cat: "Fintech & Crypto" },
  { name: "Solana", wiki: "Solana (blockchain platform)", cat: "Fintech & Crypto" },
  { name: "Monzo", wiki: "Monzo Bank", cat: "Fintech & Crypto" },
  { name: "Chime", wiki: "Chime (company)", cat: "Fintech & Crypto" },
];

// ---------- Health, Beauty & Household ----------
const HEALTH = [
  { name: "Johnson & Johnson", wiki: "Johnson & Johnson", cat: "Health & Beauty" },
  { name: "Pfizer", wiki: "Pfizer", cat: "Health & Beauty" },
  { name: "Bayer", wiki: "Bayer", cat: "Health & Beauty" },
  { name: "Colgate", wiki: "Colgate-Palmolive", cat: "Health & Beauty" },
  { name: "Oral-B", wiki: "Oral-B", cat: "Health & Beauty" },
  { name: "Listerine", wiki: "Listerine", cat: "Health & Beauty" },
  { name: "Dove", wiki: "Dove (brand)", cat: "Health & Beauty" },
  { name: "Vaseline", wiki: "Vaseline", cat: "Health & Beauty" },
  { name: "Nivea", wiki: "Nivea", cat: "Health & Beauty" },
  { name: "L'Oréal", wiki: "L'Oréal", cat: "Health & Beauty" },
  { name: "Maybelline", wiki: "Maybelline", cat: "Health & Beauty" },
  { name: "MAC Cosmetics", wiki: "MAC Cosmetics", cat: "Health & Beauty" },
  { name: "Sephora", wiki: "Sephora", cat: "Health & Beauty" },
  { name: "The Body Shop", wiki: "The Body Shop", cat: "Health & Beauty" },
  { name: "Garnier", wiki: "Garnier", cat: "Health & Beauty" },
  { name: "Pantene", wiki: "Pantene", cat: "Health & Beauty" },
  { name: "Head & Shoulders", wiki: "Head & Shoulders", cat: "Health & Beauty" },
  { name: "Old Spice", wiki: "Old Spice", cat: "Health & Beauty" },
  { name: "Gillette", wiki: "Gillette (brand)", cat: "Health & Beauty" },
  { name: "Sensodyne", wiki: "Sensodyne", cat: "Health & Beauty" },
  { name: "Band-Aid", wiki: "Band-Aid", cat: "Health & Beauty" },
  { name: "Neutrogena", wiki: "Neutrogena", cat: "Health & Beauty" },
  { name: "CeraVe", wiki: "CeraVe", cat: "Health & Beauty" },
  { name: "The Ordinary", wiki: "The Ordinary (brand)", cat: "Health & Beauty" },
];

// ---------- Industry, Energy & Logistics ----------
const INDUSTRY = [
  { name: "Caterpillar", wiki: "Caterpillar Inc.", cat: "Industry & Energy" },
  { name: "John Deere", wiki: "John Deere", cat: "Industry & Energy" },
  { name: "3M", wiki: "3M", cat: "Industry & Energy" },
  { name: "GE", wiki: "General Electric", cat: "Industry & Energy" },
  { name: "Honeywell", wiki: "Honeywell", cat: "Industry & Energy" },
  { name: "Bosch", wiki: "Robert Bosch GmbH", cat: "Industry & Energy" },
  { name: "Makita", wiki: "Makita", cat: "Industry & Energy" },
  { name: "DeWalt", wiki: "DeWalt", cat: "Industry & Energy" },
  { name: "Stanley", wiki: "Stanley Black & Decker", cat: "Industry & Energy" },
  { name: "Dyson", wiki: "Dyson (company)", cat: "Industry & Energy" },
  { name: "ExxonMobil", wiki: "ExxonMobil", cat: "Industry & Energy" },
  { name: "Chevron", wiki: "Chevron Corporation", cat: "Industry & Energy" },
  { name: "TotalEnergies", wiki: "TotalEnergies", cat: "Industry & Energy" },
  { name: "Aramco", wiki: "Saudi Aramco", cat: "Industry & Energy" },
  { name: "DHL", wiki: "DHL", cat: "Industry & Energy" },
  { name: "FedEx", wiki: "FedEx", cat: "Industry & Energy" },
  { name: "UPS", wiki: "United Parcel Service", cat: "Industry & Energy" },
  { name: "Maersk", wiki: "Maersk", cat: "Industry & Energy" },
  { name: "Tupperware", wiki: "Tupperware", cat: "Industry & Energy" },
  { name: "ZIPPO", wiki: "Zippo", cat: "Industry & Energy" },
  { name: "Rolex", wiki: "Rolex", cat: "Industry & Energy" },
  { name: "Omega", wiki: "Omega SA", cat: "Industry & Energy" },
  { name: "Patek Philippe", wiki: "Patek Philippe & Co.", cat: "Industry & Energy" },
  { name: "Casio G-Shock", wiki: "G-Shock", cat: "Industry & Energy" },
  { name: "Ray-Ban", wiki: "Ray-Ban", cat: "Industry & Energy" },
  { name: "Oakley", wiki: "Oakley, Inc.", cat: "Industry & Energy" },
  { name: "Fisher-Price", wiki: "Fisher-Price", cat: "Industry & Energy" },
];

// ---------- Telecom ----------
const TELECOM = [
  { name: "Vodafone", wiki: "Vodafone", cat: "Telecom" },
  { name: "AT&T", wiki: "AT&T", cat: "Telecom" },
  { name: "Verizon", wiki: "Verizon", cat: "Telecom" },
  { name: "T-Mobile", wiki: "T-Mobile US", cat: "Telecom" },
  { name: "Orange", wiki: "Orange S.A.", cat: "Telecom" },
  { name: "MTN", wiki: "MTN Group", cat: "Telecom" },
  { name: "Airtel", wiki: "Airtel", cat: "Telecom" },
  { name: "Jio", wiki: "Reliance Jio", cat: "Telecom" },
  { name: "O2", wiki: "O2 (UK)", cat: "Telecom" },
  { name: "Starlink", wiki: "Starlink", cat: "Telecom" },
  { name: "Safaricom", wiki: "Safaricom", cat: "Telecom" },
];

module.exports = {
  TECH, APPS, FOOD, CARS, FASHION, SPORTS, GAMING,
  RETAIL, TRAVEL, MEDIA, FINTECH, HEALTH, INDUSTRY, TELECOM,
};



